### ISSUE TITLE
Auto-complete using Racer

### ISSUE THREAD

**Issue by userxfce** [RustDT/RustDT#1]
Use this:

https://github.com/phildawes/racer

For installation:

```
cd racer; cargo build --release

Set the RUST_SRC_PATH env variable to point to the 'src' dir in your rust source installation

(e.g. % export RUST_SRC_PATH=/usr/local/src/rust/src )

Test on the command line:

./target/release/racer complete std::io::B (should show some completions)
```

Basically, is almost the same as using dcd for DDT.

Hey, congratulations and kudos!

**Comment by The-J-Person** [comment]
+1, adding autocomplete should make this the most feature-complete IDE for Rust out there

**Comment by bruno-medeiros** [comment]
Anyone else has a Window box? I couldn't get racer to work on that OS, see: https://github.com/phildawes/racer/issues/196

**Comment by userxfce** [comment]
wow. congratulations!

**Comment by userxfce** [comment]
It would be nice to have a release with this feature, especially now that Rust 1.0 is out. I am not pushing it, though...
