### ISSUE TITLE
Avoid RustDT pretty print

### ISSUE THREAD

**Issue by ghost** [RustDT/RustDT#100]
Thanks for RustDT I love it. However, when I save .rs files it changes my code to the one-true-brace style. I have a strong feeling against this even though that way is standard. Is there any way to turn this off?

Regards,
Steve

**Comment by bruno-medeiros** [comment]
Yes, you can create a rustfmt.toml file that will configure how rustfmt formats things. See https://github.com/rust-lang-nursery/rustfmt#configuring-rustfmt for more info. They have some options for brace style.
