### ISSUE TITLE
Auto-format on save repeatedly displays error popup while typing

### ISSUE THREAD

**Issue by Woyten** [RustDT/RustDT#101]
Hello everyone,

I really appreciate the inclusion of `rustfmt` into RustDT. Thanks for that! It helped me a lot keeping the code base cleaner.

I also think it is a good idea to have the auto-format on save feature available for Rust code. However, it seems to me that this feature is not working properly.

**The problem:** While I am editing a Rust source file RustDT keeps on automatically saving that file at some rate, say every 5 keystrokes. (I guess this is necessary to get real-time feedback by Rainicorn?) With the auto-format on save feature enabled, this will consequently launch `rustfmt` at the same rate. In most cases `rustfmt` will fail as the code is in an unfinished state. Unfortunately, RustDT reports the failure to the Eclipse user each time showing a popup saying _rustfmt completed with non-zero exit value..._

Looking at the Eclipse and `rustfmt` configuration I did not find any way to make Eclipse ignore `rustfmt`'s return value or to make `rustfmt` ignore broken files.

I could try to fix this issue once it is clear what the intended behavior should be. In case I missed some configuration option, we should at least communicate to the Eclipse user that he has to perform some additional action like adapting `rustfmt.toml`, etc.

Cheers,
Woyten

**Comment by bruno-medeiros** [comment]
Say what? The file keeps getting saving after a few keystrokes? That shouldn't be happening, I don't think RustDT is doing that (Rainicorn uses stdin to read the source being edited, it doesn't require the file being saved). Are you using a standard Eclipse build?

**Comment by Woyten** [comment]
I just played around with a virgin Eclipse installation and got some new insights about the problem.

My file keeps getting saved (including the `rustfmt` failure popup) whenever RustDT requests code completion via `racer`. In the default configuration this might not happen that often as you have to hit `CTRL + SPACE` before getting the completion candidates. However, in my development setup I use the _enable alphabetic characters as trigger_ option. That's why the problem also occurs during typing.

**Comment by bruno-medeiros** [comment]
ohh, I see, now that makes sense.

**Comment by bruno-medeiros** [comment]
Note that this was fixed by not invoking the format tool at all if the editor is being automatically saved because of auto-completion. I don't think the editor should be formatted in the first place just because auto-completion is invoked.

**Comment by Woyten** [comment]
Your provided solution was the first one I had in my mind but then I found that it is not perfect. If you try to save a file manually and the last action was an auto-completion no save action will be triggered again as Eclipse considers the file state as clean. This is a loophole meaning that you cannot rely on always having a pretty-formatted state (assuming compiling code). But that's what you usually want to achieve using the auto-format on save feature.

So, why is the file saved anyway? Is this some restriction of `racer`? It does not make too much sense for me as other editors like `vim` also work with `racer` and they do not need to save the file, do they?

**Comment by bruno-medeiros** [comment]
You can always invoke the formatter with `Ctrl+Shift+F`, so, I don't see it much of an issue if the file is already saved. Some IDEs (like IntelliJ IDEA, and some other web IDEs/editors) actually have removed the notion of explicit saving, instead saving is done implicitly/automatically. And I want to add this behavior to Eclipse as well. So I have submitted a patch for the Eclipse Platform code - it can't be done in RustDT alone.

You are right about having to save the file in the first place for a racer operation. I looked it up again, and there is a way to do it without having to save the file. I will make it work that way.

**Comment by Woyten** [comment]
Sounds great!
