### ISSUE TITLE
go to definition not supported for external crates

### ISSUE THREAD

**Issue by kineticz** [RustDT/RustDT#108]
One example: https://github.com/kindlychung/clipr/blob/master/src/main.rs

If you cmd-click on `ClipboardContext`, you will get a "target not found" error.

**Comment by bruno-medeiros** [comment]
It only happens for the clipboard crate, the other ones get resolved fine. It's because the clipboard crate is bound to a specific Git revision, I think.

This is a Racer issue though. I believe it's this problem: https://github.com/phildawes/racer/issues/513
