### ISSUE TITLE
Snippets from other editors

### ISSUE THREAD

**Issue by RustSnippets** [RustDT/RustDT#109]
https://github.com/zargony/atom-language-rust/blob/master/snippets/rust.cson
https://github.com/abaez/ta-rust/blob/master/snippets.lua
https://github.com/freebroccolo/rust-snippets/blob/master/rust-snippets.el
https://github.com/darookee/vim-snippets/blob/master/UltiSnips/rust.snippets
https://github.com/rust-lang/sublime-rust/tree/master/snippets

Maybe you can derive some ideas from other editors and implement it in your project.

**Comment by bruno-medeiros** [comment]
Thanks, I've added some new ones based on those.
