### ISSUE TITLE
Feature Request : Allow selecting different directories for Rust and Cargo

### ISSUE THREAD

**Issue by The-J-Person** [RustDT/RustDT#11]
Currently when I attempt to configure RustDT it asks for the Rust installation directory. When I specify it, it complains that it cannot find Cargo, but I do not have a seperate box to point it to Cargo.

I'm on an Ubuntu-based distro and using a 3rd party PPA to update my rust executable - unfortunately that PPA doesn't come with Cargo which I had to get separately from a different PPA.

In other words, they're not in the same directory on my current setup, making me unable to configure RustDT without changing everything around.

**Comment by bruno-medeiros** [comment]
At the moment RustDT only cares about the Cargo executable, so just point it to the directory that contains `bin/cargo`.

If in the future we require location Rust installation artifacts other than cargo, we might have different configuration options for each.
