### ISSUE TITLE
Old issue happening again

### ISSUE THREAD

**Issue by Phlosioneer** [RustDT/RustDT#113]
Issue #31 is happening to me.

When I make a new rust project, Eclipse can find cargo, but cargo can't find rustc. rustc is in the same directory as cargo.

RustDT version 0.6.0
RustDT installed through the Eclipse Marketplace.
Rust version 1.8.0
Rust installed via homebrew; Eclipse has the correct path: /usr/local/Cellar/rust/1.8.0/bin

The eclipse error log seems relevant:

```
!ENTRY com.github.rustdt.ide.ui 4 0 2016-05-17 16:49:56.401
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.github.rustdt.ide.ui [547]
  Unresolved requirement: Require-Bundle: com.github.rustdt.ide.core
    -> Bundle-SymbolicName: com.github.rustdt.ide.core; bundle-version="0.6.0.v201605121412"; singleton:="true"
       com.github.rustdt.ide.core [545]
         Unresolved requirement: Require-Bundle: com.github.rustdt.tooling; visibility:="reexport"
           -> Bundle-SymbolicName: com.github.rustdt.tooling; bundle-version="0.6.0.v201605121412"; singleton:="true"
              com.github.rustdt.tooling [549]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```

As in issue #31, if I start eclipse from the command line it works perfectly.

Am I setting something up wrong? It seems like this was fixed in #31, where cargo was changed to look for rustc in the same directory as it. But that's clearly not working here. And it looks like RustRDT is having all sorts of issues.

**Comment by bruno-medeiros** [comment]
Hum a lot of code related to this functionality changed, so there could be a regression here. But first of all, how is that you are even able to run RustDT if you are having that BundleException error above? That would mean RustDT failed to started at all (due to the JVM not being a 1.8 JVM). But when that happens there should be an error dialog stating that Java 8 is required.

**Comment by Phlosioneer** [comment]
I was having issues with that, and then fixed it. I did delete the log file to try and clean that error out. But maybe the delete didn't work. 

Tried it again... this time, no log file. I guess I didn't delete it properly last time. My bad.

Original issue is still happening.

**Comment by bruno-medeiros** [comment]
Ok, I can confirm there is a regression of #31 , will try to get a fix tomorrow

**Comment by Phlosioneer** [comment]
I was not able to confirm that the issue is gone. I deleted all old versions of the plugin, cloned it, built it, exported to host, restarted eclipse, and it still gives the same error.

Though it might be user error. It seems I didn't build the plugin correctly (#114)

**Comment by Phlosioneer** [comment]
It is in fact user error. Thanks for your help!
