### ISSUE TITLE
Plugin can't find path of gdb

### ISSUE THREAD

**Issue by Phlosioneer** [RustDT/RustDT#115]
When I try to debug a rust project, I get this error:

```
Error with command: gdb --version
Cannot run program "gdb": Unknown reason
```

Under debug configurations for rust, the debug gdb is set to just "gdb". It should look for gdb as if typed into the command line, i.e. look through all the path variables.

Probably related to this: #113. Like that error, if I run eclipse from the command line, it finds gdb successfully.

gdb is not located in any special place; it lives in /usr/local/bin, which is on the path variable by default, so it's not path-problems.

**Comment by Phlosioneer** [comment]
Some more information, if it's helpful: The C/C++ language pack thingy for eclipse has the same gdb settings, and doesn't find it either. Do I have something screwed up with my eclipse..?

**Comment by Phlosioneer** [comment]
Setting the gdb manually, with an absolute path, fixed the problem. I don't understand what was the issue, though.

**Comment by bruno-medeiros** [comment]
Yeah it seems like it's related to #133, it has the same root cause, which is - in Mac OS X you have a different PATH for apps started in the command line, than apps started from the UI. And GDB is likely only on the PATH of the command line.
