### ISSUE TITLE
Update Installation.md with command line installation options

### ISSUE THREAD

**Issue by dzmitry-lahoda** [RustDT/RustDT#12]
I want to deploy eclipse for rust silently. Please update doc with command line for this.

**Comment by bruno-medeiros** [comment]
`./eclipse -application org.eclipse.equinox.p2.director -repository http://rustdt.github.io/releases/ -installIU com.github.rustdt.feature.group` will install RustDT in that Eclipse installation.
Full reference of the command-line installation too: http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fp2_director.html

I'm not sure its worthwhile to put this in Installation.md
