### ISSUE TITLE
Cannot install into Eclipse Neon

### ISSUE THREAD

**Issue by HighCommander4** [RustDT/RustDT#120]
I tried installing RustDT into Eclipse Neon (the C/C++ package), but got the following error:

> Cannot complete the install because of a conflicting dependency.
>   Software being installed: RustDT 0.6.1.v201606011455 (com.github.rustdt.feature.group 0.6.1.v201606011455)
>   Software currently installed: C/C++ Development Tools 9.0.0.201606062011 (org.eclipse.cdt.feature.group 9.0.0.201606062011)
>   Only one of the following can be installed at once: 
>     C/C++ Development Platform 8.8.1.201602051005 (org.eclipse.cdt.platform.feature.jar 8.8.1.201602051005)
>     C/C++ Development Platform 9.0.0.201606062011 (org.eclipse.cdt.platform.feature.jar 9.0.0.201606062011)
>   Cannot satisfy dependency:
>     From: RustDT 0.6.1.v201606011455 (com.github.rustdt.feature.group 0.6.1.v201606011455)
>     To: org.eclipse.cdt.platform.feature.group [8.8.0,9.0.0)
>   Cannot satisfy dependency:
>     From: C/C++ Development Tools 9.0.0.201606062011 (org.eclipse.cdt.feature.group 9.0.0.201606062011)
>     To: org.eclipse.cdt.platform.feature.group [9.0.0.201606062011]
>   Cannot satisfy dependency:
>     From: C/C++ Development Platform 8.8.1.201602051005 (org.eclipse.cdt.platform.feature.group 8.8.1.201602051005)
>     To: org.eclipse.cdt.platform.feature.jar [8.8.1.201602051005]
>   Cannot satisfy dependency:
>     From: C/C++ Development Platform 9.0.0.201606062011 (org.eclipse.cdt.platform.feature.group 9.0.0.201606062011)
>     To: org.eclipse.cdt.platform.feature.jar [9.0.0.201606062011]

Perhaps some dependency version numbers need to be bumped to allow installation into Neon?

**Comment by HighCommander4** [comment]
I see this is already fixed in HEAD, it's just not reflected in the version published at https://rustdt.github.io/releases/.

**Comment by bruno-medeiros** [comment]
A new release has been published with support for the latest CDT.
