### ISSUE TITLE
No code completion for element of a Vec

### ISSUE THREAD

**Issue by HighCommander4** [RustDT/RustDT#127]
In the following code:

```
struct Point {
    x: i32,
    y: i32,
}

fn waldo(points: Vec<Point>) {
    for point in points {
        point.//here
    }
}
```

when I invoke code completion at the indicated location, I would expect to see "x" and "y" as the choices, but I get none.

**Comment by bruno-medeiros** [comment]
This would be a Racer issue, not RustDT. Probably same as: https://github.com/phildawes/racer/issues/555
