### ISSUE TITLE
Error during installation from Neon

### ISSUE THREAD

**Issue by anb0s** [RustDT/RustDT#131]
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: org.eclipse.update.feature,com.github.rustdt,0.6.2.v201607021153
No repository found containing: osgi.bundle,com.github.rustdt.ide.core,0.6.2.v201607021153
No repository found containing: osgi.bundle,com.github.rustdt.ide.debug,0.6.2.v201607021153
No repository found containing: osgi.bundle,com.github.rustdt.ide.ui,0.6.2.v201607021153
No repository found containing: osgi.bundle,com.github.rustdt.jvmcheck,1.0.0.v201607021153
No repository found containing: osgi.bundle,com.github.rustdt.tooling,0.6.2.v201607021153

**Comment by bruno-medeiros** [comment]
It seems like it might have been a temporary error, maybe Github pages had some issues for a while? Try restarting Eclipse and re-trying installation. If it still doesn't work, try the software site with plain HTTP URL, instead of HTTPS, ie: http://rustdt.github.io/releases/

**Comment by anb0s** [comment]
thanks, it worked with http://rustdt.github.io/releases/ now
