### ISSUE TITLE
"Auto build project" setting considers the project output as a library, not executable

### ISSUE THREAD

**Issue by snuk182** [RustDT/RustDT#136]
The project auto-build after file save does not work if the build target of the project is executable. By default it runs the following command:

```
cargo.exe rustc --lib -- -Zno-trans
```

which results in an error:

```
error: no library targets found
```

**Comment by bruno-medeiros** [comment]
You can change the cargo command by modifying the settings of the `check` Build Target (accessible from the Project Explorer)

**Comment by snuk182** [comment]
Accepted, working. But I'd still appreciate the separate Rust project target during the project creation (lib / exe)...
