### ISSUE TITLE
Set Target Platform

### ISSUE THREAD

**Issue by ltfschoen** [RustDT/RustDT#14]
In the Readme, under the heading **Setting up the development environment**, it explains `Setup the target platform: Open the target platform file: releng/target-platform/IDE.target and set it as your target platform.`

I do not understand how to do this. How do you "set it as your target platform" after you open the IDE.target file? Is this an option in the Eclipse Preferences menu somewhere?

**Comment by bruno-medeiros** [comment]
Just click "Set as Target platform" in the Target Definition editor:
![untitled](https://cloud.githubusercontent.com/assets/4324232/7114889/0e50a9fa-e1da-11e4-9d43-4f327fe2648e.png)

However for that editor to show up, and generally to develop Eclipse plugins, you need PDE (Platform Development Environment - https://eclipse.org/pde/). Perhaps that is what is missing.

**Comment by ltfschoen** [comment]
Thanks @bruno-medeiros. I successfully installed PDE as follows: Help > Install New Software > Work with: http://download.eclipse.org/releases/luna/ > General Purpose Tools > Eclipse Plug-in Development Environment (PDE)

After installing PDE it allowed me to open IDE.target with either Text Editor or Target Editor. Within the Target Editor I simply clicked "Set as Target Platform". It proceeded with some downloads, and after it had completed I restarted Eclipse.

However, I still get 12 errors as shown below. It appears that the Path has been set successfully for "com.github.rustdt-releng" since it contains "target-platform/IDE.target" that has been set, however the other 6 projects (i.e. "com.github.com.rustdt.ide.core", etc) do not have a Path set. How do I set the Path for these projects too? Do I simply copy/paste "target-platform/IDE.target" in the root folder of each?
![screen shot 2015-04-14 at 12 46 57 am](https://cloud.githubusercontent.com/assets/6226175/7115797/dbf88ef8-e23f-11e4-9f89-fd77aa27b41f.png)

**Comment by bruno-medeiros** [comment]
No, the target platform is a global setting, it applies to all projects in the workspace. 

Your problem is other, I suspect you need to configure the Java JRE/SDK location in Eclipse preferences: `Preferences / Java / Installed JREs`. And you need one whose version is 7 or greater.

**Comment by bruno-medeiros** [comment]
I've added a note to the README stating one needs Eclipse PDE
