### ISSUE TITLE
Error while following documented build steps

### ISSUE THREAD

**Issue by ashleysommer** [RustDT/RustDT#140]
About two months ago I followed the steps to build from source, and produced a working package.
Today I wanted to build from source again to get a current snapshot of the plugin, and I noticed the steps to build from source were a little different.

I followed the steps until the `mvn package` instruction.
That command fails with the following output:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:0.26.0:assemble-repository (default-assemble-repository) on project deps.repository: No content specified for p2 repository
```

Full output with Maven error reporting turned on: https://gist.github.com/ashleysommer/98dab2ab50ca79fbdb03e5a213631a3f

Is there something obvious that I'm doing wrong?

**Comment by bruno-medeiros** [comment]
Oh, seems like `target-platform` build fails if there is actually no dependencies. (which is the case for RustDT). I'll fix that.

Note that the above is only required for setting up a development environment for contributors. If you just want to build the latest version of RustDT (to then install it on Eclipse), you can just follow these instructions: https://github.com/RustDT/RustDT#automated-building-and-testing (basically run `mvn package` just in the root of the Git repo)
