### ISSUE TITLE
Since updating to Rust 1.12.1 the Problems view no longer updates

### ISSUE THREAD

**Issue by norru** [RustDT/RustDT#142]
Error format was improved with rustc 1.12.1 - as a result it appears that RustDT no longer parses any errors.

I'm running latest RustDT available on the update site:

RustDT  0.6.2.v201607021153 com.github.rustdt.feature.group github.com/RustDT

This is a major showstopper.

**Comment by bruno-medeiros** [comment]
I was about to say support has been added in master, but I seen you've found about it already: https://internals.rust-lang.org/t/editor-compatibility-and-the-new-error-format/3435/41

**Comment by norru** [comment]
Yep, thanks! :)
