### ISSUE TITLE
Hard to use Cargo projects that target microcontrollers

### ISSUE THREAD

**Issue by japaric** [RustDT/RustDT#145]
Disclaimer: Reporting this issue in stead of a novemb.rs participant (LeelooMinai). I haven't tried RustDT myself. But this was tested last weekend.

These kind of projects differ from normal Cargo projects in two ways:

- They use [Xargo] instead of Cargo as binary releases of core are not available for the `thumbv*m-none-eabi*` targets and Xargo builds those on the fly.

Apparently, this was not much of a problem as LeelooMinai was able to switch from Cargo to Xargo somehow though I have no idea how hard that was.

[Xargo]: https://crates.io/crates/xargo

- They pass extra arguments to the linker using the `target.thumbv*m-none-eabi*.rustflags` key in a project local `.cargo/config` file.

This last part was the real problem because, AIUI, this Eclipse plugin sets RUSTFLAGS to `--error-format=json` to be able to parse Cargo output. The issue is that setting RUSTFLAGS *overrides* the rustflags set in `.cargo/config` so the extra linker arguments never make it to `rustc` or the linker.

This last problem can be worked around by creating a custom target specification file, e.g. `cortex-m4.json`, that sets the extra linker arguments *in* the target specification file thus eliminating the need for rustflags in .cargo/config. However, this process is rather involved and error prone. It also undoes the progress of adding the `thumbv*m-none-eabi*` targets to the compiler as one of its main goals was to make users not have to mess with custom targets at all.

My understanding is that Cargo now has a `--message-format` flag that could be used instead of setting RUSTFLAGS and doing that switch would fix this rustflags problem. I think that's covered by #138.

[rustflags one usually sets in .cargo/config](https://github.com/japaric/f3/blob/master/.cargo/config)
[Some IRC discussion with @alexcrichton about this](https://botbot.me/mozilla/cargo/2016-11-23/?msg=76914982&page=1)

**Comment by bruno-medeiros** [comment]
#138 should cover that, yeah. Working on it.

**Comment by bruno-medeiros** [comment]
Closed with #138

**Comment by japaric** [comment]
@bruno-medeiros Thanks!
