### ISSUE TITLE
Json build errors are not being decoded

### ISSUE THREAD

**Issue by c410-f3r** [RustDT/RustDT#146]
Console outputs the same message, over and over:

```
...
{"message":"...","code":"...","level":"...","spans":"...","children":"...","rendered":"..."}
...
{"message":"...","code":"...","level":"...","spans":"...","children":"...","rendered":"..."}
...
```
This is the only relevant error that I found in the Error Log:

```
!ENTRY com.github.rustdt.ide.core 4 0 2016-12-04 22:12:33.972
!MESSAGE Member `def_site_span` is not a Object.
```

Any clues why is this happening? I can attach the full error log if it is necessary and I am using Eclipse 4.6.1, RustDT 0.7 and RusUp with Rust 1.13.

**Comment by bruno-medeiros** [comment]
Hum, the code handling the JSON messages has been mostly rewritten in ~master, in part in preparation for https://github.com/RustDT/RustDT/issues/138

Can you give a sample of the code that causes the RustDT problem?
Alternatively, can you build RustDT master and try your code there, see what happens? Build RustDT is relative easy, just run the Maven build: https://github.com/RustDT/RustDT#building-the-ide

**Comment by bruno-medeiros** [comment]
I've fixed the "Member `def_site_span` is not a Object", but I don't think that's what causing your problem. 

Do you get build errors from a simple project with errors (try a hello world with one errors) ?

**Comment by c410-f3r** [comment]
Thanks for the reply!

`mvn clean verify`:

```
Results :

Tests in error: 
  CargoManifest_Test.testEffectiveBinaries:51->testEffectiveBinaries$:69->testEffectiveTargets:92->CommonTestUtils.assertAreEqual:60 » AssertFailed

Tests run: 31, Failures: 0, Errors: 1, Skipped: 0
```
`mvn clean verify` builds and after installation errors are correctly decoded.

**Comment by bruno-medeiros** [comment]
OK, cool.

I'm kinda curious why the  CargoManifest_Test is failing though (that's a completely unrelated feature). It should be running fine... what OS are you running the tests in?

**Comment by c410-f3r** [comment]
Fedora 25 with maven installed via `dnf install maven`.

```
$ mvn -v
Apache Maven 3.3.9 (NON-CANONICAL_2016-07-01T11:53:38Z_mockbuild; 2016-07-01T08:53:38-03:00)
Maven home: /usr/share/maven
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-4.b16.fc25.x86_64/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "4.8.15-300.fc25.x86_64", arch: "amd64", family: "unix"
```

BTW, thanks for the new release!

**Comment by bruno-medeiros** [comment]
Closed, opened https://github.com/RustDT/RustDT/issues/150 for that other issue.
