### ISSUE TITLE
cargo check not working

### ISSUE THREAD

**Issue by guedressel** [RustDT/RustDT#151]
As a total rust newbie I installed RustDT on my Ubuntu box.
It was okay to install the required tools in the Eclipse preferences dialog (racer, ..).

But following console message was hunting me since I created a rust project through the "new project wizard":

<pre>
************  Building Rust project: hello-rust  ************
>> Running `check` with: /usr/local/bin/cargo check --message-format=json
error: no such subcommand: `check`

	Did you mean `clean`?

  ^^^ Terminated, exit code: 101 ^^^
************  Build terminated.  ************
</pre>

After some talking to google I discovered - merely coincidentally - that cargo has subcommands and that `check` is not a missing build target but such a subcommand (and it's missing on my system).
Then I ran

    $> cargo install cargo-check

And the error message in the eclipse console now looks like:

<pre>
************  Building Rust project: hello-rust  ************
>> Running `check` with: /usr/local/bin/cargo check --message-format=json
   Compiling hello v0.1.0 (file:///media/data/dev/eclipse/hello-rust)
error: Could not compile `hello`.

To learn more, run the command again with --verbose.
  ^^^ Terminated, exit code: 101 ^^^
************  Build terminated.  ************
</pre>

What am I missing now?

By the way: error marking and auto-completion do not work well in eclipse. So i think my setup is still not in the right shape.

**Comment by c410-f3r** [comment]
In my own experience, the `check` subcommand was only available in beta but I think that it will land in `1.16` according to [this issue](https://github.com/rust-lang/rust/issues/38666).

**Comment by bruno-medeiros** [comment]
Forget `cargo install cargo-check` - that is not supported. You need the `check` that is built-in to Cargo, but as mentioned above that is only available in nightly, not stable Rust (https://github.com/RustDT/RustDT/releases/tag/0.8.0)

@c410-f3r only land in 1.16? Damn, I thought it was arriving sooner, otherwise I might have delayed putting that in RustDT

**Comment by gdressel** [comment]
Thanks for telling me.
Anyways some sort of notice about this dependency on rust nightly until rust 1.16 (targeted for march 2017) for newbies like me would make starting with RustDT easier. Especially since I installed RustDT via Eclipse Marketplace and didn't see the release notes there...

**Comment by bruno-medeiros** [comment]
> Anyways some sort of notice about this dependency on rust nightly until rust 1.16 (targeted for march 2017) for newbies like me would make starting with RustDT easier. Especially since I installed RustDT via Eclipse Marketplace and didn't see the release notes there...

Yeah, I should put this in the User Guide, will do now.
