### ISSUE TITLE
Project future

### ISSUE THREAD

**Issue by c410-f3r** [RustDT/RustDT#152]
If you guys don't mind answering, would be nice to know the future directions of this project since there are many things coming for rust IDE stuff and Eclipse itself.

1. **Eclipse 4.7 will include native support for:**
   1. A generic and extensible code editor
   2. Integration with the language server protocol
2. **Rust language server protocol is in alpha stage**
3. **Eclipse Che is the "next-generation IDE" and also supports LSP**

What are you guys planning to do? Or are you guys not thinking about it right now? :P

Sources: [this](https://developers.redhat.com/blog/2016/11/24/deliver-support-for-new-languages-in-eclipse-ide-faster-with-generic-editor-and-language-servers/), [this](http://www.jonathanturner.org/2017/01/rls-alpha-release.html) and [this](http://www.infoworld.com/article/3141657/application-development/eclipse-che-cloud-ide-joins-docker-revolution.html).

**Comment by bruno-medeiros** [comment]
There are no plans to integrate with Eclipse Ché: Ché is based on a completely different platform (despite sharing the Eclipse name), so writing support for Ché would mean rewriting nearly all of RustDT! Also Eclipse Ché is not exactly a successor for the standard (desktop) Eclipse IDE, it is more of an alternative with it's target audience (cloud technologies).

As for Language Server stuff, it would be pretty cool to support that in RustDT, and take advantage of the libraries that Eclipse is developing for that (https://projects.eclipse.org/projects/technology.lsp4e). That would likely be the next best task to work on for RustDT, however, I started a full-time contract job this year, as such don't have nearly as much time to work on RustDT as before, so it doesn't look like it will happen in the near future. I'm hoping at one point I might get to add support for LSP though, but it's unclear when.

**Comment by c410-f3r** [comment]
Hey @bruno-medeiros. I was a bit invasive asking this question but I really appreciate your answer.
Anyway, this project is awesome, useful and I thank you for all the hard work you've done.
