### ISSUE TITLE
[GDB] Breakpoints don't work - "warning: can't find symbol"

### ISSUE THREAD

**Issue by ly2000k** [RustDT/RustDT#154]
I'm tring RustDT to build a hellow world rust program. After followed the RustDT installation document instructions step by step, all staffs working well but set each break point in source file will cause a "No source file named /xxx/xxx/xxx/xxx.rs" message in the debugger console and debugger don't break. The file is actually exists in the path reported by console message.

I have searched around 2 hours to find the same condition but there are no related information.

Environment IS:
* RustDT version:0.8.1.
* Eclipse IDE for C/C++ Developers version: Neon.2 Release (4.6.2) Build id: 20161208-0600.
* GDB version 7.12.1.

Detailed outputs in application console:

>> Running: /Users/charleslai/.cargo/bin/parse_describe
RUST_PARSE_DESCRIBE 1.0 {
MESSAGES {
}
Function { "main" { 2:0 6:1 } {} "()" {} }
}
  ^^^ Terminated, exit code: 0 ^^^

************  Building Rust project: mytest  ************
>> Running `build` with: /usr/local/bin/cargo build
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
  ^^^ Terminated, exit code: 0 ^^^
************  Build terminated.  ************

<terminated>(exit value:0) mytest[Rust Application] mytest
Hello, world 1!

Detailed outputs in debugger console:

GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin15.6.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
warning: `/Volumes/Work/eclipse/rsprojects/mytest/target/debug/deps/mytest-5bd867ff21cd2ee4.0.o': can't open to read symbols: No such file or directory.
warning: can't find symbol 'je_in_valgrind' in minsymtab
warning: can't find symbol 'je_chunk_alloc_dss' in minsymtab
warning: can't find symbol 'je_chunk_dss_boot' in minsymtab
warning: can't find symbol 'je_chunk_dss_postfork_child' in minsymtab
warning: can't find symbol 'je_chunk_dss_postfork_parent' in minsymtab
warning: can't find symbol 'extent_tree_ad_destroy' in minsymtab
warning: can't find symbol 'extent_tree_ad_destroy_recurse' in minsymtab
warning: can't find symbol 'extent_tree_szad_destroy' in minsymtab
warning: can't find symbol 'extent_tree_szad_destroy_recurse' in minsymtab
warning: can't find symbol 'je_extent_tree_ad_empty' in minsymtab
warning: can't find symbol 'je_extent_tree_ad_first' in minsymtab
warning: can't find symbol 'je_bt_init' in minsymtab
warning: can't find symbol 'je_opt_lg_prof_interval' in minsymtab
warning: can't find symbol 'je_opt_lg_prof_sample' in minsymtab
warning: can't find symbol 'je_opt_prof' in minsymtab
warning: can't find symbol 'je_opt_prof_accum' in minsymtab
warning: can't find symbol 'je_opt_prof_active' in minsymtab
warning: can't find symbol 'je_opt_prof_final' in minsymtab
warning: can't find symbol 'je_opt_prof_gdump' in minsymtab
warning: can't find symbol 'je_opt_prof_leak' in minsymtab
warning: can't find symbol 'je_opt_prof_thread_active_init' in minsymtab
warning: can't find symbol 'je_prof_active_get' in minsymtab
warning: can't find symbol 'je_prof_active_set' in minsymtab
warning: can't find symbol 'je_prof_alloc_rollback' in minsymtab
warning: can't find symbol 'je_prof_backtrace' in minsymtab
warning: can't find symbol 'je_prof_boot0' in minsymtab
warning: can't find symbol 'je_prof_boot1' in minsymtab
warning: can't find symbol 'je_prof_boot2' in minsymtab
warning: can't find symbol 'je_prof_free_sampled_object' in minsymtab
warning: can't find symbol 'je_prof_gdump' in minsymtab
warning: can't find symbol 'je_prof_gdump_get' in minsymtab
warning: can't find symbol 'je_prof_gdump_set' in minsymtab
warning: can't find symbol 'je_prof_idump' in minsymtab
warning: can't find symbol 'je_prof_interval' in minsymtab
warning: can't find symbol 'je_prof_lookup' in minsymtab
warning: can't find symbol 'je_prof_malloc_sample_object' in minsymtab
warning: can't find symbol 'je_prof_mdump' in minsymtab
warning: can't find symbol 'je_prof_postfork_child' in minsymtab
warning: can't find symbol 'je_prof_postfork_parent' in minsymtab
warning: can't find symbol 'je_prof_prefork' in minsymtab
warning: can't find symbol 'je_prof_reset' in minsymtab
warning: can't find symbol 'je_prof_sample_threshold_update' in minsymtab
warning: can't find symbol 'je_opt_prof_prefix' in minsymtab
warning: can't find symbol 'je_prof_gdump_val' in minsymtab
warning: can't find symbol 'lg_prof_sample' in minsymtab
warning: can't find symbol 'prof_active' in minsymtab
warning: can't find symbol 'je_quarantine' in minsymtab
warning: can't find symbol 'je_quarantine_alloc_hook_work' in minsymtab
warning: can't find symbol '_ZN104_$LT$$RF$$u27$b$u20$collections..string..String$u20$as$u20$core..str..pattern..Pattern$LT$$u27$a$GT$$GT$13into_searcher17h001149ca228e5ff7E' in minsymtab
warning: can't find symbol '_ZN116_$LT$collections..borrow..Cow$LT$$u27$a$C$$u20$str$GT$$u20$as$u20$core..ops..AddAssign$LT$$RF$$u27$a$u20$str$GT$$GT$10add_assign17h08c07e59c1a1c919E' in minsymtab
warning: can't find symbol '_ZN11collections3fmt6format17h8e988ed0004880beE' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$10trim_right17hf61516de135a2d45E' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$11into_string17h84ad0b6783cfd6c0E' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$12encode_utf1617haa4d5e79bde00b63E' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$12escape_debug17h7fd0030fb383c329E' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$12to_lowercase17hb5e9fc99c651607cE' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$12to_uppercase17h9a79ca7127cf9b79E' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$14escape_default17hd80a7c6ae8b484e2E' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$14escape_unicode17hfbaf6d3c9a311aeeE' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$4trim17h73d4627899e2f40cE' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$6repeat17h3bc37661b067de82E' in minsymtab
warning: can't find symbol '_ZN11collections3str21_$LT$impl$u20$str$GT$9trim_left17h437e2eaad23854a6E' in minsymtab
warning: can't find symbol '_ZN11collections5btree3map16unwrap_unchecked28_$u7b$$u7b$closure$u7d$$u7d$14_MSG_FILE_LINE17h402bb214ee960ef7E' in minsymtab
warning: can't find symbol '_ZN11collections5slice10merge_sort14_MSG_FILE_LINE17h8919915b6c0c92cdE' in minsymtab
warning: can't find symbol '_ZN11collections6string6String10insert_str14_MSG_FILE_LINE17hb26354a518e2fadeE' in minsymtab
warning: can't find symbol '_ZN11collections6string6String6insert14_MSG_FILE_LINE17h29f684cd53ae250bE' in minsymtab
warning: can't find symbol '_ZN11collections6string6String6remove14_MSG_FILE_LINE17h196556ec489745baE' in minsymtab
warning: can't find symbol '_ZN11collections6string6String8truncate14_MSG_FILE_LINE17h104ff35344ce888bE' in minsymtab
warning: can't find symbol '_ZN11collections6string6String9split_off14_MSG_FILE_LINE17h04442031fe852d86E' in minsymtab
warning: can't find symbol '_ZN11collections8enum_set3bit10_FILE_LINE17ha97464ef34d3b363E' in minsymtab
warning: can't find symbol '_ZN11collections8enum_set3bit15__STATIC_FMTSTR17h73e4ec96394ce8cfE' in minsymtab
warning: can't find symbol '_ZN11collections9vec_deque10wrap_index14_MSG_FILE_LINE17h3c44503ad4a2881aE' in minsymtab
warning: can't find symbol '_ZN165_$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Leaf$GT$$GT$10push_front14_MSG_FILE_LINE17hc6634d71ef1ca786E' in minsymtab
warning: can't find symbol '_ZN165_$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Leaf$GT$$GT$4push14_MSG_FILE_LINE17h1cfb113bcb9b5484E' in minsymtab
warning: can't find symbol '_ZN169_$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$GT$10push_front14_MSG_FILE_LINE17hcf8a6d15bce17d55E' in minsymtab
warning: can't find symbol '_ZN169_$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$GT$10push_front14_MSG_FILE_LINE17he617f25f84d11dc5E' in minsymtab
warning: can't find symbol '_ZN169_$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$GT$4push14_MSG_FILE_LINE17h26869f6de1d3e8d4E' in minsymtab
warning: can't find symbol '_ZN169_$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$GT$4push14_MSG_FILE_LINE17h635701583ab53bddE' in minsymtab
warning: can't find symbol '_ZN175_$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..LeafOrInternal$GT$$GT$3pop14_MSG_FILE_LINE17h8cd71706f3780bcbE' in minsymtab
warning: can't find symbol '_ZN175_$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..LeafOrInternal$GT$$GT$9pop_front14_MSG_FILE_LINE17h6ec0966d7a9f7ae9E' in minsymtab
warning: can't find symbol '_ZN178_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$BorrowType$C$$u20$K$C$$u20$V$C$$u20$NodeType$GT$$C$$u20$collections..btree..node..marker..KV$GT$$GT$6new_kv14_MSG_FILE_LINE17hcb85ed60744b4a33E' in minsymtab
warning: can't find symbol '_ZN180_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$BorrowType$C$$u20$K$C$$u20$V$C$$u20$NodeType$GT$$C$$u20$collections..btree..node..marker..Edge$GT$$GT$8new_edge14_MSG_FILE_LINE17hcc8444ecd3a2d24dE' in minsymtab
warning: can't find symbol '_ZN251_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Leaf$GT$$C$$u20$collections..btree..node..marker..Edge$GT$$GT$10insert_fit14_MSG_FILE_LINE17hac73a31fda4263d4E' in minsymtab
warning: can't find symbol '_ZN253_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..KV$GT$$GT$15bulk_steal_left14_MSG_FILE_LINE17ha19f3ccf54c6931cE' in minsymtab
warning: can't find symbol '_ZN253_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..KV$GT$$GT$15bulk_steal_left14_MSG_FILE_LINE17hac3a69c90b8db6ecE' in minsymtab
warning: can't find symbol '_ZN253_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..KV$GT$$GT$15bulk_steal_left14_MSG_FILE_LINE17hb9761d5e0493d13eE' in minsymtab
warning: can't find symbol '_ZN253_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..KV$GT$$GT$16bulk_steal_right14_MSG_FILE_LINE17h2d736c1d21752de1E' in minsymtab
warning: can't find symbol '_ZN253_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..KV$GT$$GT$16bulk_steal_right14_MSG_FILE_LINE17h9271fa20148d4281E' in minsymtab
warning: can't find symbol '_ZN253_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..KV$GT$$GT$16bulk_steal_right14_MSG_FILE_LINE17he46b251b9b4fb963E' in minsymtab
warning: can't find symbol '_ZN253_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..KV$GT$$GT$5merge14_MSG_FILE_LINE17hfa6b1df8b6824080E' in minsymtab
warning: can't find symbol '_ZN255_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..Edge$GT$$GT$10insert_fit14_MSG_FILE_LINE17h7701d90cfdf6af12E' in minsymtab
warning: can't find symbol '_ZN255_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..Edge$GT$$GT$10insert_fit14_MSG_FILE_LINE17hbfd525aee9950d4eE' in minsymtab
warning: can't find symbol '_ZN255_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..Internal$GT$$C$$u20$collections..btree..node..marker..Edge$GT$$GT$6insert14_MSG_FILE_LINE17h952d5f323fbf90d5E' in minsymtab
warning: can't find symbol '_ZN261_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..LeafOrInternal$GT$$C$$u20$collections..btree..node..marker..Edge$GT$$GT$11move_suffix14_MSG_FILE_LINE17h3ef271614b5810b9E' in minsymtab
warning: can't find symbol '_ZN261_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..LeafOrInternal$GT$$C$$u20$collections..btree..node..marker..Edge$GT$$GT$11move_suffix14_MSG_FILE_LINE17h6331815a861aa2daE' in minsymtab
warning: can't find symbol '_ZN261_$LT$collections..btree..node..Handle$LT$collections..btree..node..NodeRef$LT$collections..btree..node..marker..Mut$LT$$u27$a$GT$$C$$u20$K$C$$u20$V$C$$u20$collections..btree..node..marker..LeafOrInternal$GT$$C$$u20$collections..btree..node..marker..Edge$GT$$GT$11move_suffix14_MSG_FILE_LINE17haef2c0905f9415b8E' in minsymtab
No source file named /Volumes/Work/eclipse/rsprojects/mytest/src/main.rs.
No source file named /Volumes/Work/eclipse/rsprojects/mytest/src/main.rs.
[Inferior 1 (process 1696) exited normally]

**Comment by bruno-medeiros** [comment]
> This GDB was configured as "x86_64-apple-darwin15.6.0"

Hum, you're using OS X then? There seems to be a lot of issues with the built in GDB (essentially it doesn't work correctly). Please check this SO question for more info:
https://stackoverflow.com/questions/33162757/how-to-install-gdb-debugger-in-mac-osx-el-capitan?answertab=votes#tab-top

(it seems I have forgotten to add that SO question link to the User Guide - it got merged only on a temporary branch, I will fix that...)

PS: one way to make sure GDB breakpoints is working correctly and it's not an Eclipse/RustDT problem, is to try running GDB from command line and adding a breakpoint there, see if it works.

**Comment by ly2000k** [comment]
I have download and sign the gdb carefully, It not gdb caused. I have some clue about this now, my cargo build debug file with some external object file like mytest-1cdca6f3dd8d2390 and place them in target/debug/deps. On macos, these file has no postfix, but the main program target/debug/mytest try to find an external lib file name of mytest-1cdca6f3dd8d2390.0.o.

**Comment by bruno-medeiros** [comment]
So do you think it's a Rust/Cargo issue then, specific to OS X? It might be worth checking with the Rust forum.

**Comment by girvo** [comment]
@ly2000k Interestingly, if you point your `gdb` at the binary that lives in `target/debug/deps` it seems to work without those warnings!

**Comment by wind2412** [comment]
My problem is same. My workspace is on OSX.  If I `touch hello.rs` and `rustc -g hello.rs` and then `gdb -q hello`, there won't be any problem and load symbols successfully. However, when I use `cargo new hello --bin` and `cd hello` and `cargo build` and then `gdb -q target/debug/hello`, it will be a blast on my iterm full of messages like @ly2000k . So I can't debug the whole project at all... Of course, there's same problem on newest Eclipse Neon.3. So I think it is the rust's fault.

**Comment by bgbahoue** [comment]
I have the same issue trying to run `gdb` directly or through Visual Code

Running `gdb -q target/debug/<my exec>` give me

```
 — — Loading Rust pretty-printers — — 
Reading symbols from target/debug/hespc-site...
warning: can't find symbol 'je_in_valgrind' in minsymtab
warning: can't find symbol 'je_chunk_alloc_dss' in minsymtab
warning: can't find symbol 'je_chunk_dss_boot' in minsymtab
warning: can't find symbol 'je_chunk_dss_postfork_child' in minsymtab
warning: can't find symbol 'je_chunk_dss_postfork_parent' in minsymtab
warning: can't find symbol 'extent_tree_ad_destroy' in minsymtab
warning: can't find symbol 'extent_tree_ad_destroy_recurse' in minsymtab
warning: can't find symbol 'extent_tree_szad_destroy' in minsymtab
warning: can't find symbol 'extent_tree_szad_destroy_recurse' in minsymtab
warning: can't find symbol 'je_extent_tree_ad_empty' in minsymtab
warning: can't find symbol 'je_extent_tree_ad_first' in minsymtab
warning: can't find symbol 'je_bt_init' in minsymtab
warning: can't find symbol 'je_opt_lg_prof_interval' in minsymtab
warning: can't find symbol 'je_opt_lg_prof_sample' in minsymtab
warning: can't find symbol 'je_opt_prof' in minsymtab
warning: can't find symbol 'je_opt_prof_accum' in minsymtab
warning: can't find symbol 'je_opt_prof_active' in minsymtab
warning: can't find symbol 'je_opt_prof_final' in minsymtab
warning: can't find symbol 'je_opt_prof_gdump' in minsymtab
warning: can't find symbol 'je_opt_prof_leak' in minsymtab
warning: can't find symbol 'je_opt_prof_thread_active_init' in minsymtab
warning: can't find symbol 'je_prof_active_get' in minsymtab
warning: can't find symbol 'je_prof_active_set' in minsymtab
warning: can't find symbol 'je_prof_alloc_rollback' in minsymtab
warning: can't find symbol 'je_prof_backtrace' in minsymtab
warning: can't find symbol 'je_prof_boot0' in minsymtab
warning: can't find symbol 'je_prof_boot1' in minsymtab
warning: can't find symbol 'je_prof_boot2' in minsymtab
warning: can't find symbol 'je_prof_free_sampled_object' in minsymtab
warning: can't find symbol 'je_prof_gdump' in minsymtab
warning: can't find symbol 'je_prof_gdump_get' in minsymtab
warning: can't find symbol 'je_prof_gdump_set' in minsymtab
warning: can't find symbol 'je_prof_idump' in minsymtab
warning: can't find symbol 'je_prof_interval' in minsymtab
warning: can't find symbol 'je_prof_lookup' in minsymtab
warning: can't find symbol 'je_prof_malloc_sample_object' in minsymtab
warning: can't find symbol 'je_prof_mdump' in minsymtab
warning: can't find symbol 'je_prof_postfork_child' in minsymtab
warning: can't find symbol 'je_prof_postfork_parent' in minsymtab
warning: can't find symbol 'je_prof_prefork' in minsymtab
warning: can't find symbol 'je_prof_reset' in minsymtab
warning: can't find symbol 'je_prof_sample_threshold_update' in minsymtab
warning: can't find symbol 'je_opt_prof_prefix' in minsymtab
warning: can't find symbol 'je_prof_gdump_val' in minsymtab
warning: can't find symbol 'lg_prof_sample' in minsymtab
warning: can't find symbol 'prof_active' in minsymtab
warning: can't find symbol 'je_quarantine' in minsymtab
warning: can't find symbol 'je_quarantine_alloc_hook_work' in minsymtab
warning: `/Users/<some path>/target/debug/deps/<exec name>-b43989775abd4344.0.o': can't open to read symbols: No such file or directory.
warning: can't find symbol '_ZN5state9container9Container6unlock10_FILE_LINE17h6efdc9247e9e8101E' in minsymtab
warning: can't find symbol '_ZN69_$LT$state..storage..Storage$LT$T$GT$$u20$as$u20$core..fmt..Debug$GT$3fmt15__STATIC_FMTSTR17h94499ed595236310E' in minsymtab
done.
```

**Comment by snuk182** [comment]
Hm hm hm. If I provide an envvar `RUSTFLAGS=-g` to Rust Build, it errors out with `-g and -C debuginfo both provided`.

**Comment by snuk182** [comment]
Yes it's OSX + cargo specific. No blames for RustDT IMO.

**Comment by gilescope** [comment]
(Get the same using VS Code so definitely no blames for RustDT.)

Still, wouldn't it be great if in 2018 debugging in rust just worked?
