### ISSUE TITLE
"error: no such subcommand: `check`" after every file save

### ISSUE THREAD

**Issue by HighCommander4** [RustDT/RustDT#155]
I just installed RustDT (from the update site) on a new machine, and tried using it on some existing project code.

While the project builds successfully (via the command-line or from Eclipse), after every file-save I see the following in the console:

> 
> >> Running `check` with: /usr/local/bin/cargo check --message-format=json
> error: no such subcommand: `check`
> 
> 	Did you mean `clean`?
> 
>   ^^^ Terminated, exit code: 101 ^^^
> ************  Build terminated.  ************
> 

rustc version is 1.13.0, cargo version is 0.13.0.

**Comment by bruno-medeiros** [comment]
`cargo check` is feature that is only available in Rust nightly. I will update the doc to reflect that.

On reflection, it would have been better if the `check` Build Target was not enabled by default until this feature was fully released.

**Comment by bruno-medeiros** [comment]
`check` is now available on stable, so closing this.
