### ISSUE TITLE
Racer fails with spaces in path

### ISSUE THREAD

**Issue by pvginkel** [RustDT/RustDT#18]
If the project is in a path that contains a space, calling racer fails. The path to the file to be completed should be quoted.

**Comment by bruno-medeiros** [comment]
I've just tried it and Racer works fine in projects with spaces. The filename is already sent with as a single program argument, no need to quote.
You must be encountering a different issue. What does the Racer output show when invoked from Eclipse?

**Comment by pvginkel** [comment]
The path without quotes. Btw this is on windows.

**Comment by bruno-medeiros** [comment]
Why is it failing then - is there an error code, or are there simply no proposals shown? Can you post a screenshot of the Racer output?

**Comment by pvginkel** [comment]
I cannot reproduce this on the latest RustDT and Racer. Maybe it was due to a problem in Racer.
