### ISSUE TITLE
Content Assist not function 

### ISSUE THREAD

**Issue by sbant** [RustDT/RustDT#19]
I have installed 0.2.0.v201504232210

set these config:
Directory: E:\Rust
Rust 'src' Directory: E:\rustc-nightly
Executable: E:\racer.exe

When I type 'std'  '::' or anything, no Content Assist displayed. But I can use F3 to jump to the code declare.

When build the project, eclipse often blocked at Building Workspace: (0%) (Build all... Invoking 'Rust builder' on '/Project'.),any other operation can't contiune include exit eclipse(I have to kill the eclipse executable)

---

Edit:
Content Assist can now displayed with 'Alt + /'

May I suggest RustDT add function to display Content Assist when click any key?

**Comment by bruno-medeiros** [comment]
'Alt + /' is not Content Assist, but Word Completion (it just looks up words that appear in that text file, but it doesn't do anything Rust specific)

Content Assist is invoked with 'Ctrl-Space' . I could add a feature to make it auto-activate automatically, when characters are typed. Opened:  https://github.com/RustDT/RustDT/issues/23

**Comment by bruno-medeiros** [comment]
It seems the correct directory for `Rust 'src' Directory:` should be `E:\rustc-nightly\src` . When you configured the `Rust 'src' Directory:` in the preferences page, was there any warning given in the preference page?

**Comment by sbant** [comment]
sorry, mistyped
Rust 'src' Directory: E:\rustc-nightly\src

And the block when Building is still there

**Comment by bruno-medeiros** [comment]
Try Content Assist right after this text: `std::` to see if it works. What happens? Do you get any results, do you at least get snippet proposals? (since these don't involve Racer)

As for build problem, that is very strange... RustDT should not freeze Eclipse like that, since it is merely calling an external program. Do you have other Eclipse plugins installed, other than RustDT? These could be interfering. Please try again with only RustDT installed. If it still freezing, please post the contents of the Eclipse log.

**Comment by sbant** [comment]
In Eclipse Installation Details
I have only Eclipse IDE for C/C++ Developers and RustDT

In Preferences -> General -> Keys
The default of Content Assist key is actually 'Alt+/' ,I never change it
As I know 'Ctrl-Space' is language switch in Windows
And as I edited in first comment, I can use Content Assist now with 'Alt+/'

*_EDITED to https://github.com/RustDT/RustDT/issues/26 *_

**Comment by bruno-medeiros** [comment]
This is too confusing to track two issues, so I've opened a new one for the build problem: https://github.com/RustDT/RustDT/issues/26

As for Content Assist, again, if you it right after this text: `std::` to see if it works. What happens? Do you get any results, do you at least get snippet proposals?

**Comment by sbant** [comment]
Content Assist is ok now
