### ISSUE TITLE
lifetimes are incorrectly hilighted as char

### ISSUE THREAD

**Issue by oli-obk** [RustDT/RustDT#2]
everything after a lifetime tick `'` is highlighted until either the end of line or the next lifetime tick as if it were a character

**Comment by userxfce** [comment]
isn't this fix worthy of a release? I am not sure if important, but for sure it was annoying...

**Comment by userxfce** [comment]
many thanks for your work.

**Comment by bruno-medeiros** [comment]
Yeah, I'll do a release soon, in the next few days.
