### ISSUE TITLE
Whenever I press ctrl + space I get a weird error

### ISSUE THREAD

**Issue by posix4e** [RustDT/RustDT#22]
Just installed the eclipse-java-luna-SR2-linux-gtk-x86_64.tar.gz and installed the dt plugin. Now whenever I press ctrl+space I get Tool exited with non-zero status 127.

**Comment by bruno-medeiros** [comment]
> If there is a problem with these operations, and you need a diagnostics log, the output of Racer can be seen in the `RustDT Racer log` console page in the Eclipse Console view.

Check that console log to see the output of Racer and figure out what the error is.

**Comment by posix4e** [comment]
I see I must be doing it wrong
***********\*  Building Rust workspace  ************
-------   Building Rust project: test123  -------

> > Running: /home/posix4e/rust_nightly/bin/cargo build
> >    Compiling hello_world v0.0.1 (file:///home/posix4e/workspace3/test123)
> > src/main.rs:5:2: 6:12 error: expected macro name without module separators
> > src/main.rs:5   Box::
> > src/main.rs:6     println!("Hello, world!");
> > error: aborting due to previous error
> > Could not compile `hello_world`.

To learn more, run the command again with --verbose.
  ^^^ Terminated, exit code: 101 ^^^
***********\*  Build terminated.  ************

How do I do autocomplete?

**Comment by bruno-medeiros** [comment]
That's the output of the `Rust build` console, it's not the Racer output. The Racer log console looks like this, and is under the page `RustDT Racer log`:
![untitled](https://cloud.githubusercontent.com/assets/4324232/7377602/5fb4031c-eddf-11e4-9883-aab0bd4a2e09.png)

**Comment by posix4e** [comment]
Let's close this. It seems to be fixed in newer versions.
