### ISSUE TITLE
Enhancement: Auto activate Content Assist when characters are typed.

### ISSUE THREAD

**Issue by bruno-medeiros** [RustDT/RustDT#23]
Add Auto activate Content Assist when characters are typed. (configurable with pref options)

**Comment by userxfce** [comment]
This would be so convenient to have!

**Comment by userxfce** [comment]
For the record, equivalent options in CDT are: Window->Preferences->C/C++->Editor->Content Assist->Auto-activation

![contentassist](https://cloud.githubusercontent.com/assets/663793/7444942/c5cd07fa-f19c-11e4-9f2f-6459336d90e4.png)

**Comment by userxfce** [comment]
This is of a great help. Is a release being considered?
