### ISSUE TITLE
Cannot use debug under ubuntu, gdb: unrecognized option '-iex'

### ISSUE THREAD

**Issue by uniquejava** [RustDT/RustDT#25]
Hello,Bruno. I was trying to debug my rust application, after i clicked the debug button(or debug as ...), I got below error messages. (However, I can debug my c/c++ project without any issue and also i can **run** my rust application)

Error in services launch sequence
gdb: unrecognized option '-iex'

![selection_068](https://cloud.githubusercontent.com/assets/1049271/7416144/da6d1510-ef8f-11e4-8a09-b921159b8f92.png)

I checked my debugger settings, it's the same as the screen shot in the user guide.

Also could you help me understanding this note?

> Note that for debugging to work, the program must be compiled with debug symbols information, and those debug symbols must be on a format that GDB understands. Otherwise you will get GDB error messages such "(no debugging symbols found)" or "file format not recognized".

I am quite new to Rust and GDB.  Could you give an example on this. Thanks.

**Comment by bruno-medeiros** [comment]
What GDB version you have? I don't know when the '-iex' option was introduced, but you probably need GDB 7.7 or greater

**Comment by bruno-medeiros** [comment]
Needs more info.
