### ISSUE TITLE
Build operation freezes/blocks for a long time.

### ISSUE THREAD

**Issue by bruno-medeiros** [RustDT/RustDT#26]
QUOTING @sbant

For the build problem
My code already built, then I type a 'space' and then 'Ctrl+s' 'Ctrl+b' to build it.

the Console display:
***********\*  Building Rust workspace  ************
-------   Building Rust project: MarketData  -------

> > Running: E:\Rust\bin\cargo.exe build
> > ##    Compiling MarketData v0.0.1 (file:///Z:/MarketData)
> > 
> > ...
> > compiler outputs
> > ## ...
> > 
> >   ^^^ Terminated, exit code: 0 ^^^

The Building Workspace window is display like:
Building all...
Invoking 'Rust builder' on '/Project'.

the Eclipse consume 100% cpu in one core, and memory usage growing at the same time.
Then other operation must wait the block disappear.

I can't even Cancel the Building Workspace.
When I clicked 'Cancel' button, 
the Details display:
Building Workspace (Cancel Requested)
Building all...: Invoking 'Rust builder' on '/Project'.

What only I can do is wait...

After about one minute, then the Console display:
***********\*  Build terminated.  ************

Then the block stopped, other operation can contiune

**Comment by bruno-medeiros** [comment]
Hum, it seems like there could be a bug or performance issue when RustDT parses the build output, such that it makes it take a long time to finish. Can you post or attach here the build output in that scenario?

**Comment by sbant** [comment]
Cause my project use FFI
There are lots of #[warn(dead_code)], #[warn(unused_variables)], #warn(non_upper_case_globals)], etc...

I feel Eclipse consume a lot of time to update the hints in editor and others.
Maybe it's the problem of Eclipse, not RustDT.

**Comment by bruno-medeiros** [comment]
Hum, odd. I'll try to take another look at the underlying DDT code to see if I can spot any performance bug, but I don't imagine what it could be... 
Is your project an open-source one? It would help me greatly I could try building your Rust code myself.

**Comment by sbant** [comment]
I have upload my code, the CTP_Wrapper.rar is the "C"  dll rust to call

Link removed

**Comment by bruno-medeiros** [comment]
Thanks, I've been able to replicate it now. Will see about debugging it later.
