### ISSUE TITLE
Preferences page "Rust" unclear

### ISSUE THREAD

**Issue by genodeftest** [RustDT/RustDT#29]
The preferences page "Rust" is unclear: I don't know which directories to choose for "Directory" or "Rust 'src' Directory".

"Rust 'src' Directory" reveals (after writing a path into it) that it wants something where a directory named libcore resides. Problem: There is no such directory installed by the rust installer. There only is a libcore-4e7c5e5c.rlib file (archive) in /usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib and /usr/local/lib/rustlib/i686-unknown-linux-gnu/lib.

Also it would be quite nice to auto-search for those directories as "Java" → "Installed JREs" does.

Using RustDT 0.2.0.v201504232210

**Comment by Matvey-Kuk** [comment]
+1

**Comment by bruno-medeiros** [comment]
Hum, I thought I had added that to the UserGuide, apparently I didn't. Basically you need to download the Rust sources, a separate archive, for the 'src' field. It's silly that it's not included in the standard Rust distribution, yes. An issue for that problem has been opened on the Rust tracker: https://github.com/rust-lang/rust/issues/19535

**Comment by armink** [comment]
+1

**Comment by bruno-medeiros** [comment]
Clarified in the UserGuide Configuration section https://github.com/RustDT/RustDT/blob/latest/documentation/UserGuide.md#configuration
