### ISSUE TITLE
feature request: support `cargo test`

### ISSUE THREAD

**Issue by oli-obk** [RustDT/RustDT#3]
to run `cargo test` you need to add an external tool and give it the exact path to `cargo.exe`. It would be very comfortable to have a `Rust Test` target that can be created like an `Rust Application` target.

**Comment by NobbZ** [comment]
This can get extended to `cargo update` and `cargo doc` as well, but probably not as a Run-Target but as an additional command from context menu of the project/cargo-files.

**Comment by oli-obk** [comment]
for `update` the context menu is fine, but if you are testing or trying out the look of the docs, you should be able to simply run the last target.

**Comment by pvginkel** [comment]
Even better would be a more full featured unit test implementation. A lot of code is developed starting from a unit test. At the moment there is no way to make use of the debugger integration from a unit test.

Unit test integration like the following would be ideal:

![](http://oopbook.com/wp-content/uploads/2012/10/junit8.png)

Barring that, at least a way to run all unit tests or a specific unit test (even one entered by name somewhere) would be terrific. I know the unit test executable `cargo` creates has such an option through the `--run` argument.

Associated with this, a way to define constants would also help a lot. The unit test code is normally placed under a `#[cfg(test)]`. RustDT currently only compiles (if I'm correct) release versions which means no errors are reported for code that's behind a `#[cfg(test)]`.

**Comment by freeman42x** [comment]
+1 This would be really nice to have.

**Comment by llogiq** [comment]
Not only this, but library development in RustDT is currently somewhat limited.

**Comment by pvginkel** [comment]
I've ended up routing all functionality through a program/main so I can at
least just run it. Some minimal functionality to run tests (like eg
changing the cargo command line from "run" to something user defined) would
be great for the time being.

**Comment by bruno-medeiros** [comment]
Essentially implemented now.

**Comment by freeman42x** [comment]
@bruno-medeiros Is there any information of how to use the implemented functionality? Is this console only or does it support the testing GUI?

**Comment by bruno-medeiros** [comment]
> @bruno-medeiros Is there any information of how to use the implemented functionality? Is this console only or does it support the testing GUI?

Oh, it's implement in the Git master of RustDT, but not on any released version yet. It will be available very soon though.

**Comment by bruno-medeiros** [comment]
> @bruno-medeiros Is there any information of how to use the implemented functionality? Is this console only or does it support the testing GUI?

Oh, it's implement in the Git master of RustDT, but not on any released version yet. A release will be available very soon though.

**Comment by freeman42x** [comment]
And is this console only text output or does it support the testing GUI
with the tree view, etc?

**Comment by bruno-medeiros** [comment]
Console only, although build errors from test source will show up in the editor like other errors. There is no Tests view like what @pvginkel posted. (You can open an enhacement request issue for that if you want)

**Comment by freeman42x** [comment]
Thank you, can't wait to try it.

@pvginkel Would you like to open a ticket about having an integrated Eclipse GUI test runner like in your picture (and provide a link here if you do)? :)
