### ISSUE TITLE
Can't build project (Could not execute process `rustc -vV` (never executed))

### ISSUE THREAD

**Issue by idmitrievsky** [RustDT/RustDT#31]
Hello!
I am having a problem on build:

```
************  Building Rust workspace  ************
-------   Building Rust project: krpc-rs  -------
>> Running: /usr/local/bin/cargo build
Could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
  ^^^ Terminated, exit code: 101 ^^^
************  Build terminated.  ************
```

I think `cargo` can't see `rustc`, which is strange, because they are in the same directory.
Any ideas on how fix this? :disappointed:

**Comment by Matvey-Kuk** [comment]
I have the same issue on Mac Os X :(

**Comment by idmitrievsky** [comment]
@Matvey-Kuk I am running OS X too. Also I have [multirust](https://github.com/brson/multirust) installed, but I don't think it has anything to do with this, because all executables are in place.

**Comment by Matvey-Kuk** [comment]
I used default rust installation script

**Comment by alienjun** [comment]
Failed to create a child process.
Cannot run program "/Users/xxx/workspace/Rust/HelloWorld/src/main.rs" (in directory "/Users/xxx/workspace/Rust/HelloWorld"): error=13, Permission denied

***********\*  Building Rust workspace  ************
-------   Building Rust project: HelloWorld  -------

> > Running: /usr/local/Cellar/rust/1.0.0/bin/cargo build
> > Could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
  ^^^ Terminated, exit code: 101 ^^^
***********\*  Build terminated.  ************

**Comment by alienjun** [comment]
I have the same issue on Mac Os X

**Comment by mfreiwald** [comment]
Same here
Mac OS X 10.10.3
Eclipse Luna 4.4.1
rustc 1.2.0-nightly (0cc99f9cc 2015-05-17) (built 2015-05-17)
cargo 0.2.0-nightly (ac61996 2015-05-17) (built 2015-05-17)

Running command in Terminal does compile successfully

**Comment by bruno-medeiros** [comment]
Seems like an issue specific to Mac OS X. Unfortunately I don't have any Mas OS X box available ATM to try it. However with Goclipse there was some users which had similar problems (with `go build` not being able to invoke the compiler), and it seems it was related to Mac OS X having different environments (like environment vars) for processes started from the command line, and processes started from the app launcher.

Could you guys try starting Eclipse from the command line, and see how that works out?

**Comment by idmitrievsky** [comment]
@bruno-medeiros it seems to work just fine in Eclipse started from the command line.

**Comment by bruno-medeiros** [comment]
Then it could be issue I was thinking of. It might be that Eclipse started from the GUI doesn't have the PATH env var setup with the Rust bin directory. See this comment for more detail about this OSX issue: https://github.com/GoClipse/goclipse/issues/91#issuecomment-82555504 
I can make a workaround in RustDT (just as in Goclipse) to automatically add the Rust installation dir to PATH when starting Cargo, but better yet would be if Cargo was smart enough to try to find rustc in the same directory as the cargo executable.

**Comment by idmitrievsky** [comment]
Great to know it's fixable. 
How fast does cargo team fix such problems? Maybe best solution is implementing a workaround for now and creating an issue in cargo project.

**Comment by Matvey-Kuk** [comment]
May be, this issue is related? https://github.com/rust-lang/cargo/issues/987

**Comment by bruno-medeiros** [comment]
> May be, this issue is related? rust-lang/cargo#987

Thanks for finding that out, seems like it is.

**Comment by bruno-medeiros** [comment]
I think I've fixed this with a workaround, but can't verify it myself since I don't have OS X around. Can someone with this problem try it out? You'd need to download and build RustDT yourself, but that should be fairly easy:
- Download Maven (http://maven.apache.org/)
- `git clone https://github.com/RustDT/RustDT.git`
- `cd RustDT`, `mvn package`
- You should now have an update site in `bin-maven/features.repository/repository` Just update your RustDT installation using that local dir as an update site and try it out. (don't worry, you can revert your RustDT installation in Eclipse in `Help / About Eclipse / Installation Details / Installation History`, if the built RustDT version has problems)

**Comment by Matvey-Kuk** [comment]
@bruno-medeiros thank you! I've done all as you said, but now everything is broken totally =) There is "No editor descriptor for id com.github.rustdt.ide.ui.editor.RustEditor" error in editor window... I think, I've done smth wrong. May be somebody more experienced in java instruments should try?... @ivandmitrievsky ? @mfreiwald ? @alienjun ?

**Comment by bruno-medeiros** [comment]
I think i know why that is. Are you running Eclipse with Java 7? The new RustDT version requires Java 8. Stupidly there is no error message if that is not the case,the plugin just fails to load...

**Comment by idmitrievsky** [comment]
It finds `rustc` now! Thanks a lot for fixing this :+1:

**Comment by Matvey-Kuk** [comment]
@bruno-medeiros , now awaiting for release =)

**Comment by alienjun** [comment]
The new RustDT version requires Java 8? my java -version like this:
alienjunx$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by bruno-medeiros** [comment]
> The new RustDT version requires Java 8? my java -version like this:
> alienjunx$ java -version
> java version "1.8.0_31"

Then it should work. Did you still have problems starting RustDT?

**Comment by martin-magakian** [comment]
@mfreiwald same problem for me.
Starting eclipse from the command line worked.

**Comment by bruno-medeiros** [comment]
This fix is out now. For those that didn't try it from a source build, try it with the release, and let me know if you have any issues.

**Comment by amiracam** [comment]
I seem to have a related issue. New to Rust and overall pretty new to Eclipse , I mostly use Idea. Anyhow in my case I encounter the issue when trying to "Run as" the project . Just trying to test the hello world  app.

see error output:

Failed to create a child process.
Cannot run program "/Users/charles/Documents/rust_workspace/RustTest/src/main.rs" (in directory "/Users/charles/Documents/rust_workspace/RustTest"): error=13, Permission denied

I'm on the latest RustDT and i have the requisite Java version i.e. > 1.8.x

thanks for the feedback

**Comment by amiracam** [comment]
hi, I opened up the permissions on main.rs and I got past this error but now encounter a strange syntax error , strange since that file was generated by RustDT itself . here's the error:

/Users/charles/Documents/rust_workspace/RustTest/src/main.rs: line 1: syntax error near unexpected token `('
'Users/charles/Documents/rust_workspace/RustTest/src/main.rs: line 1:`fn main() {

any clues ?

**Comment by amiracam** [comment]
I also have encountered a problem with gdb , it does seem that RustDT is not seeing it i.e.

Error with command: gdb --version
Cannot run program "gdb": Unknown reason

I have confirmed that otherwise I can see gdb

**Comment by bruno-medeiros** [comment]
> Failed to create a child process.
> Cannot run program "/Users/charles/Documents/rust_workspace/RustTest/src/main.rs" (in directory "/Users/charles/Documents/rust_workspace/RustTest"): error=13, Permission denied

The RustDT launch configuration should be configured with the executable generated by Cargo (something like `target/debug/RustTest.exe`), not the .rs file. The error above is because the launch tried to start the .rs file as a process directly.

**Comment by bruno-medeiros** [comment]
> Error with command: gdb --version
> Cannot run program "gdb": Unknown reason

Are you on OS X ?

**Comment by amiracam** [comment]
yes sir, 
Charles Monteiro

**Comment by bruno-medeiros** [comment]
The GDB that is included with OS X doesn't work properly. You'll need to install the latest GDB from Homebrew (the MacPorts one doesn't work either, I suspect). See this for details: http://ntraft.com/installing-gdb-on-os-x-mavericks/

**Comment by amiracam** [comment]
but I did, i.e. found instructions on how to do that and Mac OS X does provide me with confirmation of a successful install i.e.

Charless-Mini:~ charles$ gdb --version
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Charless-Mini:~ charles$ 

Charles Monteiro

**Comment by bruno-medeiros** [comment]
> but I did, i.e. found instructions on how to do that and Mac OS X does provide me with confirmation of a successful install i.e.

And are you sure that's the one that RustDT is using for debugging? Did you set the path to that GDB in the "GDB debugger" field of the launch configuration:  https://raw.githubusercontent.com/RustDT/RustDT/latest/documentation/screenshots/UserGuide_DebuggerLaunchConfiguration.png ?

**Comment by amiracam** [comment]
I am not sure , I left that path referred to by the provided pic alone i.e. its the default. GDB was not present in my system prior to the installation that I just did in order to support RustDT , so I believe its the only one and thus should be located here:

Charless-Mini:~ charles$ which gdb
/usr/local/bin/gdb
Charless-Mini:~ charles$ 

btw, I’m also having issues running the app , perhaps related ? something about Mac OS X support ?

See here:

/Users/charles/Documents/rust_workspace/RustTest/src/main.rs: line 1: syntax error near unexpected token `('
'Users/charles/Documents/rust_workspace/RustTest/src/main.rs: line 1:`fn main() {

the code is simply this:

fn main() {

```
println!("Hello, world!");
```

}

thanks, I appreciate your help getting me up and running , I’m too used to using IDEs in my professional help, that its hard to contemplate taking on learning Rust without IDE and debugging support.

Charles Monteiro

**Comment by bruno-medeiros** [comment]
What does the build console say after you try building that project?

**Comment by amiracam** [comment]
maybe some progress, the default points to an alias, instead I set it up to point to the gdb exec directly , then upon engaging the debugger I got this different output:

Error in final launch sequence
Failed to execute MI command:
-file-exec-and-symbols /Users/charles/Documents/rust_workspace/RustTest/src/main.rs
Error message from debugger back end:
"/Users/charles/Documents/rust_workspace/RustTest/src/main.rs": not in executable format: File format not recognized
"/Users/charles/Documents/rust_workspace/RustTest/src/main.rs": not in executable format: File format not recognized

Charles Monteiro

**Comment by amiracam** [comment]
a “build all” generates this:

====================  Starting Rust build  ====================
***********\*  Building Rust project: RustTest  ************

> > Running: /usr/local/bin/cargo build
> >   ^^^ Terminated, exit code: 0 ^^^
> > ***********\*  Build terminated.  ************

Charles Monteiro

**Comment by bruno-medeiros** [comment]
> "/Users/charles/Documents/rust_workspace/RustTest/src/main.rs": not in executable format: File format not recognized

Seems as if you are trying to run the .rs file as if it is an executable. The launch configuration must be configured with an executable file (the "Program Path" field) . Try starting the launch in Run mode (not Debug) and see if that works first of all.

**Comment by bruno-medeiros** [comment]
> a “build all” generates this:
> 
> ====================  Starting Rust build  ====================
> ***********\*  Building Rust project: RustTest  ************
> 
> > Running: /usr/local/bin/cargo build
> > ^^^ Terminated, exit code: 0 ^^^
> > ***********\*  Build terminated.  ************

That's weird. Then no error should appear in the Rust source editor. Can you send me a screenshot of the error in the editor?

**Comment by amiracam** [comment]
sure:

Running:

Debugging:

thanks

Charles Monteiro

**Comment by bruno-medeiros** [comment]
There's no image attached to your post. If you sent it from email, it might have not worked because of that.
Also, could you open a new issue please, post the images/info there.

**Comment by amiracam** [comment]
Yes copied straight to mail , usually works , ill start new issue, thanks

**Comment by amiracam** [comment]
Bruno:

I figured out how to get your latest :) , and my “run” issue is gone. however I have an issue when trying to debug where I can’t see the source i.e. I get “View Dissassembly” so, when I go to debug configuration it seems that the source tab is specifying defaults.

thanks

Charles Monteiro

**Comment by bruno-medeiros** [comment]
Please open new issues for new issues. :hammer:
