### ISSUE TITLE
Add autocompletion for attributes

### ISSUE THREAD

**Issue by Virviil** [RustDT/RustDT#38]
No ideas, how to do this, but if you can show me how to manage this i can try to add this kind of autocompletion. For such code as
`#[allow(dead_code)]` 
for example.

**Comment by bruno-medeiros** [comment]
This should be added into Racer itself.

**Comment by bruno-medeiros** [comment]
Yeah, this would need to be added to Racer itself: https://github.com/phildawes/racer
