### ISSUE TITLE
Don't show error dialog when Racer fails

### ISSUE THREAD

**Issue by pvginkel** [RustDT/RustDT#41]
With the latest version, Racer is automatically run by default. When Racer returns an error, a message dialog pops up. When this does happen, it tends to happen a lot. Beyond that, even though there probably is an issue with Racer (in my case it's telling me `MATCHSTR is empty - waddup?`), it mostly just gets in the way of my development.

I guess I think it would be a good idea to simply suppress the message box. If it is necessary to communicate a Racer error to the developer, maybe a better idea is to put focus on the Racer Console. That way you see the problem instead of just clicking away an irritating message box.

**Comment by bruno-medeiros** [comment]
Hum, I don't recall ever been able to make my Racer process return an error. Which source did you use to make that happen?

As a workaround, you can disable the auto-activation of Content Assist in the RustDT preferences.

**Comment by pvginkel** [comment]
I get this lots of times, most of the time when I'm editing in the middle
of a large file. I haven't taken the time to reproduce this, but that
shouldn't matter. The point is that when racer panics, a message box is
displayed. If it's important I could try to create a reproducable scenario
but I'm not sure when I'll have the chance to do this. You probably could
easily get the message box by simply putting a panic in racer's main though.

**Comment by bruno-medeiros** [comment]
Ah, I know how this issue would occur, I don't need the steps to reproduce... I was asking more for curiosity of what Racer was doing.

I agree, a message dialog seems like a too obtrusive of a UI notification for this.

**Comment by pvginkel** [comment]
Ah OK. Yeah I've looked at the racer logs a few times but basically there
are a lot of different messages. It happens to me roughly every 10 minutes.
Maybe I'm just writing strange code. One of the reasons may be that I have
a few impls spread out over different files. Racer doesn't seem to like
that.

**Comment by bruno-medeiros** [comment]
Hum, actually this fixes only suppresses the error dialog if the Racer exit value is non-zero. Do you have any situation where Racer errors out somehow, but still terminates with a zero exit value?
