### ISSUE TITLE
PATH of external tools bungled if original PATH not set (Windows)

### ISSUE THREAD

**Issue by kirillkh** [RustDT/RustDT#43]
I've encountered the following issue (Windows-only?): instead of passing the system PATH value to cargo for building, RustDT passes two variables:

PATH=null;H:\devel\rust1.0\bin
Path=#the real stuff#

Trying to figure out what causes the bug, I arrived at the method: melnorme.lang.utils.ProcessUtils.addDirToPathEnv()

Assuming at the entry point of this method the environment variable is called "Path" and not "PATH", executing the method would result in the observed behavior. I have confirmed this as follows: I substituted racer.exe executable for an exetutable that prints the environment variables. When run by RustDT, it shows Path=#the real stuff# (and when run outside, it shows PATH as expected).

Now the puzzling part is how exactly "PATH" gets transformed into "Path" inside Eclipse. I have not been able to figure this out. Trying to reproduce it with a test Java program outside of Eclipse doesn't show this behavior (it shows PATH, not Path). Here is the program: https://gist.github.com/kirillkh/9b9d432c591712378086

**Comment by kirillkh** [comment]
Update: just looking at the environment variables from cmd.exe, I see "Path" and not "PATH". I guess some tools take care to capitalize all the letters (including the standard Java 8 library and MSYS), which led me to believe the problem was inside Eclipse. Changing the environment variable to "PATH" in Windows settings fixed the problem for me.

**Comment by bruno-medeiros** [comment]
Thanks for spotting it, I've been able to replicate it. There are two bugs involved here:
- the PATH env var is set under with a name with a case different than "PATH" (in Window this is valid)
- the PATH env var is not set at all
