### ISSUE TITLE
RustDT installation documentation is confusing

### ISSUE THREAD

**Issue by antonkulaga** [RustDT/RustDT#46]
The installation section of documentation is confusing (that ate 30 mins of my time, cause I had to google), because
1) It does not tell me that I have to separately download  rustd sources to make racer work, so I expected them to be somewhere after installing Linux binaries of rust language.
2) It does not tell me all the things I should put in my Rust preferences
3) Part of installation text is moved to user_guide that looks strange
4) No words about what I should add to program path in my run configuration
5) Why cannot it look at system path and try to extract RUST path variables so users should not add them manually?

**Comment by bruno-medeiros** [comment]
Thanks, that's some good points there.

**Comment by bruno-medeiros** [comment]
Let me know if you have additional suggestions. Point 4) will be addressed in the UI itself, not the documentation.
