### ISSUE TITLE
Unknown line format: - Could not match expr node

### ISSUE THREAD

**Issue by koutheir** [RustDT/RustDT#47]
While editing code, I got this message box, and its contents are:

> Unknown line format: - Could not match expr node type: ExprMac(Spanned { node: MacInvocTT(path(vec), [TtToken(Span { lo: BytePos(31), hi: BytePos(42), expn_id: ExpnId(4294967295) }, Ident(Philosopher#0, ModName)), TtToken(Span { lo: BytePos(42), hi: BytePos(44), expn_id: ExpnId(4294967295) }, ModSep), TtToken(Span { lo: BytePos(44), hi: BytePos(47), expn_id: ExpnId(4294967295) }, Ident(new#0, Plain)), TtDelimited(Span { lo: BytePos(47), hi: BytePos(65), expn_id: ExpnId(4294967295) }, Delimited { delim: Paren, open_span: Span { lo: BytePos(47), hi: BytePos(48), expn_id: ExpnId(4294967295) }, tts: [TtToken(Span { lo: BytePos(48), hi: BytePos(64), expn_id: ExpnId(4294967295) }, Literal(Str_("              "(65)), None))], close_span: Span { lo: BytePos(64), hi: BytePos(65), expn_id: ExpnId(4294967295) } }), TtToken(Span { lo: BytePos(65), hi: BytePos(66), expn_id: ExpnId(4294967295) }, Comma), TtToken(Span { lo: BytePos(73), hi: BytePos(84), expn_id: ExpnId(4294967295) }, Ident(Philosopher#0, ModName)), TtToken(Span { lo: BytePos(84), hi: BytePos(86), expn_id: ExpnId(4294967295) }, ModSep), TtToken(Span { lo: BytePos(86), hi: BytePos(89), expn_id: ExpnId(4294967295) }, Ident(new#0, Plain)), TtDelimited(Span { lo: BytePos(89), hi: BytePos(107), expn_id: ExpnId(4294967295) }, Delimited { delim: Paren, open_span: Span { lo: BytePos(89), hi: BytePos(90), expn_id: ExpnId(4294967295) }, tts: [TtToken(Span { lo: BytePos(90), hi: BytePos(106), expn_id: ExpnId(4294967295) }, Literal(Str_("              "(65)), None))], close_span: Span { lo: BytePos(106), hi: BytePos(107), expn_id: ExpnId(4294967295) } }), TtToken(Span { lo: BytePos(107), hi: BytePos(108), expn_id: ExpnId(4294967295) }, Comma), TtToken(Span { lo: BytePos(115), hi: BytePos(126), expn_id: ExpnId(4294967295) }, Ident(Philosopher#0, ModName)), TtToken(Span { lo: BytePos(126), hi: BytePos(128), expn_id: ExpnId(4294967295) }, ModSep), TtToken(Span { lo: BytePos(128), hi: BytePos(131), expn_id: ExpnId(4294967295) }, Ident(new#0, Plain)), TtDelimited(Span { lo: BytePos(131), hi: BytePos(144), expn_id: ExpnId(4294967295) }, Delimited { delim: Paren, open_span: Span { lo: BytePos(131), hi: BytePos(132), expn_id: ExpnId(4294967295) }, tts: [TtToken(Span { lo: BytePos(132), hi: BytePos(143), expn_id: ExpnId(4294967295) }, Literal(Str_("         "(66)), None))], close_span: Span { lo: BytePos(143), hi: BytePos(144), expn_id: ExpnId(4294967295) } }), TtToken(Span { lo: BytePos(144), hi: BytePos(145), expn_id: ExpnId(4294967295) }, Comma), TtToken(Span { lo: BytePos(152), hi: BytePos(163), expn_id: ExpnId(4294967295) }, Ident(Philosopher#0, ModName)), TtToken(Span { lo: BytePos(163), hi: BytePos(165), expn_id: ExpnId(4294967295) }, ModSep), TtToken(Span { lo: BytePos(165), hi: BytePos(168), expn_id: ExpnId(4294967295) }, Ident(new#0, Plain)), TtDelimited(Span { lo: BytePos(168), hi: BytePos(191), expn_id: ExpnId(4294967295) }, Delimited { delim: Paren, open_span: Span { lo: BytePos(168), hi: BytePos(169), expn_id: ExpnId(4294967295) }, tts: [TtToken(Span { lo: BytePos(169), hi: BytePos(190), expn_id: ExpnId(4294967295) }, Literal(Str_("                   "(67)), None))], close_span: Span { lo: BytePos(190), hi: BytePos(191), expn_id: ExpnId(4294967295) } }), TtToken(Span { lo: BytePos(191), hi: BytePos(192), expn_id: ExpnId(4294967295) }, Comma), TtToken(Span { lo: BytePos(199), hi: BytePos(210), expn_id: ExpnId(4294967295) }, Ident(Philosopher#0, ModName)), TtToken(Span { lo: BytePos(210), hi: BytePos(212), expn_id: ExpnId(4294967295) }, ModSep), TtToken(Span { lo: BytePos(212), hi: BytePos(215), expn_id: ExpnId(4294967295) }, Ident(new#0, Plain)), TtDelimited(Span { lo: BytePos(215), hi: BytePos(234), expn_id: ExpnId(4294967295) }, Delimited { delim: Paren, open_span: Span { lo: BytePos(215), hi: BytePos(216), expn_id: ExpnId(4294967295) }, tts: [TtToken(Span { lo: BytePos(216), hi: BytePos(233), expn_id: ExpnId(4294967295) }, Literal(Str_("               "(68)), None))], close_span: Span { lo: BytePos(233), hi: BytePos(234), expn_id: ExpnId(4294967295) } })], 0), span: Span { lo: BytePos(19), hi: BytePos(238), expn_id: ExpnId(4294967295) } }, Bracket)

The rust source contents was:

``` rust
use std::thread;
struct Philosopher { name : String }
impl Philosopher {
    fn new(name: &str) -> Philosopher {
        Philosopher { name: name.to_string() }
    }
    fn eat(&self) {
        println!("{} started eating.", self.name);
        thread::sleep_ms(1000);
        println!("{} is done eating.", self.name);
    }
}

fn main()
{
    let philosephers = vec![
        Philosopher::new("Baruch Spinoza"),
        Philosopher::new("Gilles Deleuze"),
        Philosopher::new("Karl Marx"),
        Philosopher::new("Friedrich Nietzsche"),
        Philosopher::new("Michel Foucault")
    ];

    let thread_handles: Vec<_> = philosephers.into_iter().

    for p in &philosephers {
        p.eat();
    }
}
```

The editing was begin done on the line containing:

``` rust
let thread_handles: Vec<_> = philosephers.into_iter().
```

**Comment by bruno-medeiros** [comment]
Opened a Racer bug for this: https://github.com/phildawes/racer/issues/323

Not much to be done in RustDT side. Although I do wonder if I should show error dialogs for invalid Racer syntax, or just display the error in the editor status.

**Comment by koutheir** [comment]
The message box is not enough to display such large amounts of text. I suggest putting that in editor status of error list.

**Comment by bruno-medeiros** [comment]
The user is not meant to read the full error text in the message box anyways. The purpose is only to report that has been an internal error in Racer. I'd rather such issues that are likely Racer bugs are not ignored silently, but reported to the user so they can be reported back to Racer... but this approach can be a problem if it's some errors happen often but are not fixed quickly in Racer.

**Comment by koutheir** [comment]
Makes sense. Just be sure the Racer error can be identified as such to ease reporting to Racer community.

**Comment by bruno-medeiros** [comment]
Yeah the full ouput is available in the Racer Eclipse console anyways
