### ISSUE TITLE
Avoid displaying dialogs for errors relating to auto-completion

### ISSUE THREAD

**Issue by Diggsey** [RustDT/RustDT#48]
A problem with autocompletion shouldn't interrupt the programmer's typing - it's fine for errors to just show in the status bar.

**Comment by freeman42x** [comment]
:+1: This would be really helpful as it breaks the flow of typing too many times. And disabling the autocomplete or setting a higher autocomplete timeout is not really that good of a solution.

**Comment by bruno-medeiros** [comment]
Duplicate of #41
