### ISSUE TITLE
No source available for "main() at 0x4090d8

### ISSUE THREAD

**Issue by freeman42x** [RustDT/RustDT#50]
On launch of debug mode a new tab showing `No source available for "main() at 0x4090d8` was opened:

![](http://i.imgur.com/j8hKnJ3.png)

The solution was to uncheck `Stop on startup at` under the Debug configuration settings:

![](http://i.imgur.com/bEdVjP8.png)

**Comment by bruno-medeiros** [comment]
Opened #51 for this
