### ISSUE TITLE
Better defaults for Debugger "Stop at startup:" option

### ISSUE THREAD

**Issue by bruno-medeiros** [RustDT/RustDT#51]
Currently the option is enabled by default for C's `main`, but stopping here is not of much use for Rust programs

**Comment by pvginkel** [comment]
Easiest is to just disable it and use function break points. I always have
one on rust_panic and you can put one on your own main. I'm however not
sure what to name it because of name mangling.

**Comment by userxfce** [comment]
This can be raised in the discussion with nrc from the Rust team.

**Comment by bruno-medeiros** [comment]
> This can be raised in the discussion with nrc from the Rust team.

Huh, what exactly would be raised with nrc?

**Comment by userxfce** [comment]
Sorry. I was referring to issue #58 (to discuss the name mangling and the initial breakpoint address with the rustc compiler team, in particular Nick Cameron aka nrc).

**Comment by bruno-medeiros** [comment]
Oh this has actually been fixed already
