### ISSUE TITLE
Focus Console window on build

### ISSUE THREAD

**Issue by freeman42x** [RustDT/RustDT#54]
It would be nice to have a setting to focus Console window (and/or perhaps Problems window) on build.

**Comment by freeman42x** [comment]
[Programmatically showing a View from an Eclipse Plug-in](http://stackoverflow.com/q/171824/750216)

**Comment by freeman42x** [comment]
Ah, it seems that the Console is focused when there is an error, if there is not error it will not be focused.

**Comment by freeman42x** [comment]
It actually does not focus when running a console application, so an option would be nice.

**Comment by bruno-medeiros** [comment]
When you launch a Rust application you mean? yeah it does focus the process console, please recheck that.
