### ISSUE TITLE
Talk to nrc and the tools sub-team

### ISSUE THREAD

**Issue by nrc** [RustDT/RustDT#58]
@bruno-medeiros  Hi, sorry to file an issue for this, but I couldn't find an email address or any other way to contact you. We (the Rust team at Mozilla and the tools and compiler sub-teams) are thinking about how we can better offer IDE support and how the compiler can help. It would be really useful to chat to you about Rust DT and about what you could use from the compiler. Could you drop me an email please? nrc@mozilla.com.

Cheers!

**Comment by bruno-medeiros** [comment]
No a prob raising an issue, I'll get in touch soon.
