### ISSUE TITLE
Debug: Automatically set up rust-gdb Rust GDB pretty-printers

### ISSUE THREAD

**Issue by bruno-medeiros** [RustDT/RustDT#6]
See https://github.com/rust-lang/rust/blob/master/src/etc/rust-gdb for reference.

Note: setting rust-gdb as the debugger in Eclipse won't work as a workaround, since rust-gdb is a shell script and not an executable. But putting the equivalent commands in the `.gdbinit` file should work.

**Comment by michaelwoerister** [comment]
I can confirm that the Rust pretty printers can be made to work with RustDT, by using a custom `.gdbinit` file and making sure the PYTHONPATH includes the pretty printers. I know too little about Eclipse to make this more ergonomic. But it should be possible to additional arguments and environment entries when starting the GDB subprocess, right?

**Comment by bruno-medeiros** [comment]
> But it should be possible to additional arguments and environment entries when starting the GDB subprocess, right?

Yes, but it's not trivial, extending CDT to work in this way is not always easy. However, the alternative of modifying `.gdbinit` is something that can be done already in the released RustDT / CDT, because each launch configuration can specify a custom .gdbinit: https://github.com/RustDT/RustDT/blob/master/documentation/screenshots/UserGuide_DebuggerLaunchConfiguration.png

**Comment by bruno-medeiros** [comment]
Actually, I took a look at it, and this one seems relatively easy actually. I can trivially modify GDB's start arguments, or alternatively make it load a second ".gdbinit" file of my own (even a temporary file that the IDE could create on each launch - it would be invisible to the user).

Haven't tried it yet though.

**Comment by bruno-medeiros** [comment]
I didn't manage to get this working in Windows, dunno if it's even possible. It doesn't auto-load the script, and even when I force loading of the script with a gdb `source` command, it fails with some weird error (a python error I think)

**Comment by bruno-medeiros** [comment]
I didn't manage to get this working in Windows though, dunno if it's even possible. It doesn't auto-load the script, and even when I force loading of the script with a gdb source command, it fails with some weird error (a python error I think). I tried with latest TDM-GCC and MinGW-w64-x86_64-4.9.2-posix-seh-rt_v4-rev2
