### ISSUE TITLE
Java 8 Dependency is an Issue to me

### ISSUE THREAD

**Issue by ArthurZ** [RustDT/RustDT#60]
It wasn't stated anywhere that RustDT will fail to start if no Java 8 is present as set as the default (Ubuntu 14.04), but I have other tools that require Java 7. So it looks like the catch 21 situation.

**Comment by bruno-medeiros** [comment]
Well, you can have multiple Java installations, so install Java 8, in addition to Java 7. Then, you can control which one Eclipse uses with the "-vm" startup parameter. For more details see `Specifying the Java virtual machine` in http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Frunning_eclipse.htm
