### ISSUE TITLE
Feature request: Multiple build environments

### ISSUE THREAD

**Issue by Koka** [RustDT/RustDT#63]
It would be nice to have multiple build environments (rustc, cargo, racer, etc.) simultaneously and have an ability to quickly switch build environment for particular project.

As far as I can understand, for now I can't simultaneously have two projects in a single workspace - one compiled with rust-nightly and another with rust-stable 1.2 for example. I has to change paths in Rust preference page every time I want switch from stable rust to nightly.

JDT have similar feature named "Installed JREs" which allows register all the java installations you have and assign them to your projects later.

![jre_defs](https://cloud.githubusercontent.com/assets/100578/9577578/1516de42-4feb-11e5-8feb-3091d983bf07.png)

**Comment by bruno-medeiros** [comment]
Hum, should be fairly easy to add a per-project Rust installation override.

**Comment by bruno-medeiros** [comment]
Agreed, and it should be fairly easy to implement a per-project Rust installation settings.

**Comment by Diggsey** [comment]
Also the ability to customize the environment variables set before invoking cargo/rustc!

**Comment by bruno-medeiros** [comment]
I've implemented it, but @Diggsey , one still can't sent any environment variables for the Rust tools, whether is per-project or globally. Why do you want such a feature?

**Comment by Diggsey** [comment]
There are several ways environment variables can affect the build. Custom build scripts often look at environment variables, and normal code can use the `env!` macros.

My particular case was setting several `OPENSSL_xxx` variables before invoking cargo. These are used by the `openssl-sys` crate's build script, and are used to decide whether to statically or dynamically link openssl, and where to look for the openssl libraries and include files.

**Comment by bruno-medeiros** [comment]
Ugh, it's ugly as hell to use environment variables to customize a build script like that. Still, if you're using a third party library, it's not your fault... I guess the IDE should support use cases like that. Opened https://github.com/RustDT/RustDT/issues/72 (not high priority at the moment though)
