### ISSUE TITLE
Feature Request: Option for not compiling on each save

### ISSUE THREAD

**Issue by rkyoku** [RustDT/RustDT#65]
While probably useful to some people, "build on file save" is actually not what I would like to do.

If I modify several files at the same time, I will have to save the first file (randomly) which will make the plugin try to build and - obviously - fail my app, or worse it will try to build and I will save another file before it finishes, which will queue build tasks, and I'll have to stop them manually each time I modify/save a file...

I would prefer to be able to choose if/when I want to build.

Is it be possible to add an option in preferences->rust? It would be very welcome!

Thank you in advance for your help,

**Comment by userxfce** [comment]
The build is linked with the autocomplete and/or the code analyzer, I think, although it should be enough that the racer alone gets called. The developer knows more about this. Maybe an useful option, besides the one that you mention, is to allow such build only at "save all" action.

**Comment by bruno-medeiros** [comment]
This is already available as an Eclipse setting : disable `Project / Build Automatically`

**Comment by rkyoku** [comment]
Thank you Bruno, I will try that! But then again, maybe it would be nice to
allow the user to choose, for example, if the "tests" build should be
launched too, because it is uselessly longer in most cases (we may only
want to launch the tests build only before a commit on the develop branch,
for example, to make sure nothing is broken)

Thanks anyway!

Le lun. 21 sept. 2015 à 14:46, Bruno Medeiros notifications@github.com a
écrit :

**Comment by bruno-medeiros** [comment]
@RenaudParis 

Check the picture here: https://users.rust-lang.org/t/the-rustdt-eclipse-ide-thread/2087/4
You can disable the tests build by unchecking the `Enable for workspace build`option. (The workspace build is the build of the entire Eclipse workspace that happens when you press Ctrl-B or save a file)

The tests build will still be build when you run/debug a test target/executable.

**Comment by rkyoku** [comment]
Mmmh very nice! I am sorry I asked these questions without looking hard
enough apparently! Thank you Bruno!

Le lun. 21 sept. 2015 à 20:12, Bruno Medeiros notifications@github.com a
écrit :
