### ISSUE TITLE
Everything marked as unused after upgrade

### ISSUE THREAD

**Issue by ghost** [RustDT/RustDT#73]
Since the upgrade to rust 1.3 and V3 of RustDT my main fn is marked as unused (and so everything else).
Yes my program compiles and runs smoothly. I've selected non-test build.
Telling RustDT to create a non-test build manually works, but in the editor the yellow "unused" marks are staying.
Debian 8, Eclipse Mars, RustDT 0.3.0.v201508261428 (latest update from plugin "store")

This seems to come from the fact that the test build is enforced & always happens after a complete build.

![unbenannt](https://cloud.githubusercontent.com/assets/10698040/10713044/37f85f6a-7aae-11e5-8764-a1a607a27fc8.png)
![unbenannt](https://cloud.githubusercontent.com/assets/10698040/10713045/43b8402c-7aae-11e5-8b64-46a959755008.png)

**Comment by ghost** [comment]
The problems is fixed by marking test-builds not enabled for workspace builds.
Please add this to the manual as I'm probably not the only one confused from this behaviour when no test case is existent.
![unbenannt](https://cloud.githubusercontent.com/assets/10698040/10713074/5ae91202-7aaf-11e5-83b0-4255ccc6526d.png)

**Comment by bruno-medeiros** [comment]
Note: this warning about `main` being unused when building `crate#tests` no longer happens with Rust 1.4 .
