### ISSUE TITLE
No smart indention support for official rust; Formarly (Set smart indention to use matching brace )

### ISSUE THREAD

**Issue by RichardlL** [RustDT/RustDT#76]
Right now, if i delete a closing bracket in a existing code block Eg

```
fn foo() ->bar {
        //stuff
}  //   <- -  delete this
```

When If i have smart deletion and insertion turned on, it does this when try to reinsert it.

```
fn foo()  -> bar { 
        //stuff 
        }  /* it uses the line above it, which is even more of a problem if smart delete
 is enabled, as  it just puts it back on the "stuff" comment line */
```

What i propose is check if the first non space/tab charachter on the active line is a closing brace (rectroactiely, you would have to check for editing of  the first charater of a line in addition to making a new line), and if it is, match the indention to the matching braces line (if available) , instead of the line above it

**Comment by bruno-medeiros** [comment]
I'm a bit confusing about which scenario exactly you are trying to change. Are you saying that with the code:

```
fn foo() ->bar {
        blah()}
```

and one presses Enter with the cursor between "blah()" and "}", you want to get this:

```
fn foo() ->bar {
        blah()
}
```

instead of what RustDT currently does: 

```
fn foo() ->bar {
        blah()
        }
```

**Comment by RichardlL** [comment]
Yes, that is what I mean. I havent seen that style before, I thought it was a bug, Haha.  Though it would still be helpfull to be able to choose that, as both of those two would cover most brace styles (Including the official rust style :P ).
-  No matching
  -  Would Support:
    - Whitesmiths,
    - Lisp,
    - Ratliff (RustDT style)
    - Pico
- smart matching
  - Matches:
    -  K&R (which is  the offical rust syle see: https://aturon.github.io/style/whitespace.htm)
    -  Allman
    -  WhiteSmith
    -  GNU
    -  Allman,
    - Stroustrup
    - Linux kernel
    - 1TBS
    -  bsd KNF

From: https://en.wikipedia.org/wiki/Indent_style

\* Offical Rust style supports line  wrapping, like bsd KNF; see:  https://aturon.github.io/style/braces.html#opening-braces-always-go-on-the-same-line., to Conditonally support all these, and rust style, the logic would look something like 

```

if   Allign = smart  // allign option
         for (lineVar = closing brakets line, ParaCount = 0;  lineVar != OpenBracket Line ; lineVar--)
         {
               if  (find closing paranthesis on lineVar)  close  +=  closing parantheses on linevar;
               if (find open paranthesis on lineVar) close  -= opening paranthesis on lineVar;
               if  (closing == 0
                     AND NO -> statement found  LineVar 
                     AND have seen Opening bracket )   //you would probably have to ciount brackets too
                     {
                         allign to first non space/tab on linevar;
                         break;
                     } 
          }
```

This would account all of the "smart" indent styles, accounting for wrapping, and tuples, and special cases like these : 

```
foobar
           .foo()
           .bar() 
           .inter()
           .map ( | |  {

            }); //alligns correctly here.  a method with a closure has paranthesis around it, 
                // so it starts with -1
 //not here

From Rust style Guide 

fn frobnicate(a: Bar, b: Bar, // Acceptable
              c: Bar, d: Bar)   // Close = 1
              -> Bar {  // " ->" found 
    ...
}  

```

**Comment by RichardlL** [comment]
I dont know java too well, but If you could point me to where input is parsed to check for indention, I could probably submit a pull request sometime this week.

**Comment by bruno-medeiros** [comment]
It is a bug. Or rather a limitation, such functionality wasn't implement. The intended style is K&R (or Allman). You can see it in the example where you have

```
fn foo() ->bar { 
```

then press Enter after "{", and the result will be this: (where ¦ is the cursor location)

```
fn foo() ->bar { 
    ¦
}
```

in other words the end brace is added automatically.

**Comment by bruno-medeiros** [comment]
> I dont know java too well, but If you could point me to where input is parsed to check for indention, I could probably submit a pull request sometime this week.

I would have welcomed that, but I ended up already adding such functionality yesterday..
