### ISSUE TITLE
Some dependency conflictions occured while installing 

### ISSUE THREAD

**Issue by K-Meow** [RustDT/RustDT#78]
Seems RustDT can not be installed on Eclipse IDE for Mobile Developers because of some dependency conflictions.

Here is the error message:

Cannot complete the install because of a conflicting dependency.
  Software being installed: RustDT 0.4.2.v201511271555 (com.github.rustdt.feature.group 0.4.2.v201511271555)
  Software currently installed: Eclipse IDE for Mobile Developers 1.5.0.20120614-1633 (epp.package.mobile 1.5.0.20120614-1633)
  Only one of the following can be installed at once: 
    Eclipse e4 Workbench Add-ons 0.10.3.v20130124-185622 (org.eclipse.e4.ui.workbench.addons.swt 0.10.3.v20130124-185622)
    Eclipse e4 Workbench Add-ons 0.10.1.v20120827-151636 (org.eclipse.e4.ui.workbench.addons.swt 0.10.1.v20120827-151636)
    Eclipse e4 Workbench Add-ons 0.10.1.v20120523-1955 (org.eclipse.e4.ui.workbench.addons.swt 0.10.1.v20120523-1955)
    Eclipse e4 Workbench Add-ons 1.2.0.v20150512-1414 (org.eclipse.e4.ui.workbench.addons.swt 1.2.0.v20150512-1414)
  Cannot satisfy dependency:
    From: RustDT 0.4.2.v201511271555 (com.github.rustdt.feature.group 0.4.2.v201511271555)
    To: org.eclipse.platform.feature.group [4.5.0,5.0.0)
  Cannot satisfy dependency:
    From: Eclipse IDE for Mobile Developers 1.5.0.20120614-1633 (epp.package.mobile 1.5.0.20120614-1633)
    To: org.eclipse.epp.package.mobile.feature.feature.group [1.5.0.20120614-1633]
  Cannot satisfy dependency:
    From: Eclipse e4 Rich Client Platform 1.1.0.v20120521-2329-8yFTIGF3GGduEYqkQB9M3DKn (org.eclipse.e4.rcp.feature.group 1.1.0.v20120521-2329-8yFTIGF3GGduEYqkQB9M3DKn)
    To: org.eclipse.e4.ui.workbench.addons.swt [0.10.1.v20120523-1955]
  Cannot satisfy dependency:
    From: Eclipse e4 Rich Client Platform 1.4.0.v20150603-0857 (org.eclipse.e4.rcp.feature.group 1.4.0.v20150603-0857)
    To: org.eclipse.e4.ui.workbench.addons.swt [1.2.0.v20150512-1414]
  Cannot satisfy dependency:
    From: Eclipse e4 Rich Client Platform 1.4.0.v20150903-1804 (org.eclipse.e4.rcp.feature.group 1.4.0.v20150903-1804)
    To: org.eclipse.e4.ui.workbench.addons.swt [1.2.0.v20150512-1414]
  Cannot satisfy dependency:
    From: EPP Mobile Package 1.5.0.20120614-1633 (org.eclipse.epp.package.mobile.feature.feature.group 1.5.0.20120614-1633)
    To: org.eclipse.platform.feature.group [4.2.0.v20120608-135145-9JF7BHV8FyMteji0Oi_ePMz0xuZ8TVo7lV0z0ecb]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.2.0.v20120608-135145-9JF7BHV8FyMteji0Oi_ePMz0xuZ8TVo7lV0z0ecb (org.eclipse.platform.feature.group 4.2.0.v20120608-135145-9JF7BHV8FyMteji0Oi_ePMz0xuZ8TVo7lV0z0ecb)
    To: org.eclipse.rcp.feature.group [4.2.0.v20120528-1648-7IAPA7BrHQicRpNdOz-Obz-rlRCA]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.5.0.v20150603-2358 (org.eclipse.platform.feature.group 4.5.0.v20150603-2358)
    To: org.eclipse.rcp.feature.group [4.5.0.v20150603-2331]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.5.1.v20150904-0015 (org.eclipse.platform.feature.group 4.5.1.v20150904-0015)
    To: org.eclipse.rcp.feature.group [4.5.1.v20150904-0015]
  Cannot satisfy dependency:
    From: Eclipse RCP 4.2.0.v20120528-1648-7IAPA7BrHQicRpNdOz-Obz-rlRCA (org.eclipse.rcp.feature.group 4.2.0.v20120528-1648-7IAPA7BrHQicRpNdOz-Obz-rlRCA)
    To: org.eclipse.e4.rcp.feature.group [1.1.0.v20120521-2329-8yFTIGF3GGduEYqkQB9M3DKn]
  Cannot satisfy dependency:
    From: Eclipse RCP 4.5.0.v20150603-2331 (org.eclipse.rcp.feature.group 4.5.0.v20150603-2331)
    To: org.eclipse.e4.rcp.feature.group [1.4.0.v20150603-0857]
  Cannot satisfy dependency:
    From: Eclipse RCP 4.5.1.v20150904-0015 (org.eclipse.rcp.feature.group 4.5.1.v20150904-0015)
    To: org.eclipse.e4.rcp.feature.group [1.4.0.v20150903-1804]

**Comment by bruno-medeiros** [comment]
Eclipse for Mobile Developers seems to be a fairly old Eclipse package (from Juno release, which is from 2012). You need to download a recent Eclipse package, Eclipse Mars (4.5) is the minimum. The "Eclipse for Mobile Developers" package appears to be discontinued, but maybe Eclipse IDE for C/C++ Developers covers it ?
