### ISSUE TITLE
Build Target for other platform support

### ISSUE THREAD

**Issue by ghost** [RustDT/RustDT#79]
A feature to build for another OS, even if only by running the CMD over SSH on a VM would be helpful.
I don't know how approachable this is with eclipse but it would be very helpful.

**Comment by bruno-medeiros** [comment]
What exactly do you want to build for another OS? RustDT itself? Or Cargo crates?

**Comment by ghost** [comment]
I would want to write Rust-Code via the Eclipse-IDE and build it on another machine.
So the warnings/failures shown by RustDT are from the build-process on the other machine.

**Comment by bruno-medeiros** [comment]
No, it's not possible at the moment. Although you could create a fake Cargo/Rust installation with a cargo command that would transparently run the actual cargo build on a different machine, and then output the warnings/errors as normal to RustDT

**Comment by bruno-medeiros** [comment]
This issue should be resolved with the new functionality in master, that allows a Built Target to run an arbitrary tool, not just Cargo.
