### ISSUE TITLE
Import from existing cargo

### ISSUE THREAD

**Issue by NobbZ** [RustDT/RustDT#8]
It would be nice if we could import a project from a given cargo-file

**Comment by oli-obk** [comment]
you can do that already, just select the location of your cargo file as the project root

**Comment by userxfce** [comment]
If this is the case, then I think at least a tip in the dialog window and a pop-up window detecting a pre-existing project and asking for importing would be needed.

Alternatively, provide a separate "Create from existing"-style menu option.

**Comment by oli-obk** [comment]
uhm... I was under the impression that the way it is in RustDT it is how it's done in eclipse in general

**Comment by oli-obk** [comment]
see http://stackoverflow.com/a/9280568/1103681

**Comment by userxfce** [comment]
At least for Eclipse CDT (C/C++), there is an explicit "File"->"New"->"Makefile Project with Existing Code"

Why this? Usually, Eclipse generates its own Makefile, that might overwrite the original Makefile (or not use it at all, thus making all the configuration therein useless).

**Comment by oli-obk** [comment]
well... that assumes `Cargo.toml` is an equivalent to a `Makefile`. But `Cargo.toml` is more of a `.project` file than a `Makefile`. If the File->New->"With Existing Cargo.toml" does the same as selecting the location, then i vote for not offering both, as users might expect one to behave differently from another

**Comment by NobbZ** [comment]
Eclipse told me that I can't do that because that folder had already some
content.
Am 27.02.2015 12:37 schrieb "Oliver Schneider" notifications@github.com:

**Comment by userxfce** [comment]
@oli-obk If Cargo.toml is the equivalent of a .project, then there is already the option: "File"->"Import"->"Existing Projects into Workspace" that should be used.

**Comment by bruno-medeiros** [comment]
@NobbZ What is the exact error message? Did you use the `Rust / Rust Cargo Project` wizard?

@oli-obk I originally thought about a mechanism that would automatically make any Eclipse project a RustDT project if a Cargo.toml file was added or removed, but there was some technical issues with that so it didn't make it in initial release.

**Comment by oli-obk** [comment]
didn't know that was possible. Although cool, I assume since most people don't know about it, they would still wonder how to import projects.

**Comment by bruno-medeiros** [comment]
I've added that note the UserGuide: https://github.com/RustDT/RustDT/blob/latest/documentation/UserGuide.md#project-creation
