### ISSUE TITLE
Autcomplete Regression

### ISSUE THREAD

**Issue by ghost** [RustDT/RustDT#80]
On v. 0.2.0 (it's what I can assure), Razer was able to auto-complete call from own mods.
Let's say I've a lib::{some functions} which are public, which is also imported via `use`.
Atm it's not finding any self declared functions any more. Autocomplete isn't completely broken as it's still finding std and functions of traits which are in use.
This could be related to razer, if so feel free to ignore this and close it.

Edit:
`self.` autocomplete also doesn't work -> "No proprosals"

Path is linked to the actual executable, Rust 1.3, current eclipse market version of RustDT
Occours with latest source-build of razer and the v1.0.0

According to razer, it is called without rust lib support:

``` log
>> Running: /home/dev/Downloads/razer/racer-master/racer complete-with-snippet 152 21 /mnt/hgfs/Rust/my-project/src/lib/mod.rs
PREFIX 21,21,
MATCH download;download;149;6;/mnt/hgfs/Rust/my-project/src/lib/mod.rs;FnArg;download
MATCH downloader;downloader;1;0;/mnt/hgfs/Rust/my-project/src/lib/downloader.rs;Module;/mnt/hgfs/Rust/my-project/src/lib/downloader.rs
MATCH downloader;downloader;1;0;/mnt/hgfs/Rust/my-project/src/lib/downloader.rs;Module;/mnt/hgfs/Rust/my-project/src/lib/downloader.rs
END
```

Leading to this:
![unbenannt](https://cloud.githubusercontent.com/assets/10698040/11454876/4b30715a-9640-11e5-8891-6d42ea841b3e.png)
This is clearly a PathBuf, which gets auto completed with an own struct.

**Comment by bruno-medeiros** [comment]
It's likely this is a Racer issue, not RustDT. Can you try with the latest Racer version? Not Racer v1.0.0, but the latest from master.

If it doesn't work, can you provide a simple source code example illustrating the problem.

**Comment by ghost** [comment]
As stated above it's occurring with the latest version also, I'm always building from the master branch.

I'll give it another try today.

**Comment by ghost** [comment]
I've rebuild it again from master and now it seems to work. ( own functions are found again & std-completion works now also )
I can't say what caused this.

Thanks for RustDT & your time !
