### ISSUE TITLE
Path to the installation

### ISSUE THREAD

**Issue by AlexRadch** [RustDT/RustDT#83]
What path to the installation I should configure?
Path to Rust installation `root folder` (`"C:\Program Files\Rust stable GNU 1.6\"` for example on my windows) ?
Or to bin folder or to lib folder or some other folder?

**Comment by bruno-medeiros** [comment]
Yes, it's the root folder. If you had tried any different folder (like bin), the preferences dialog will show an error saying it can't find cargo.exe
