### ISSUE TITLE
How to download Rust sources package?

### ISSUE THREAD

**Issue by AlexRadch** [RustDT/RustDT#84]
You wrote that I need Rust sources package (see Rust bug https://github.com/rust-lang/rust/issues/19535).
But in this bug (https://github.com/rust-lang/rust/issues/19535) I do not see any instructions how do download Rust sources package.

How to download Rust sources package on Windows?

**Comment by noreabu** [comment]
It seems the path to the source has changed to:

https://www.rust-lang.org/en-US/other-installers.html#source

I suggest reopening this issue, but i can also create another one or make a pull request, if you prefer that.

**Comment by bruno-medeiros** [comment]
With Rust 1.15 having now `rustup` as the official installation method, the way to install source has also changed. Now one should use ` rustup component add rust-src` (https://github.com/rust-lang/rust/issues/19535#issuecomment-279101566)
The RustDT docs need to be updated, will do that later
