### ISSUE TITLE
Can not download Rainicorn tool

### ISSUE THREAD

**Issue by AlexRadch** [RustDT/RustDT#87]
When I try download Rainicorn tool, I got next error on Windows: 

```
Error executing `Download Rainicorn parse_describe`.
HOME environment variable not set.
```

![2016-02-16_17-32-02](https://cloud.githubusercontent.com/assets/6407980/13075150/57b4a1cc-d4d3-11e5-8f01-df84022e274c.png)

The same error is if try to download Racer tool. I installed it manually.

How to install Rainicorn tool? Here https://github.com/RustDT/Rainicorn I don't see any instructions.

**Comment by bruno-medeiros** [comment]
Run `cargo install --git https://github.com/RustDT/Rainicorn --tag version_1.x`

As for HOME error, it's same issue as this: https://github.com/RustDT/RustDT/issues/82
