### ISSUE TITLE
How to configure Eclipse debugger on Windows to find Rust sources?

### ISSUE THREAD

**Issue by AlexRadch** [RustDT/RustDT#89]
Why I got next error `No source available for "main() at 0x4015ca"` when I try to debug program?
Debugger can not find source file!

![eclipse_2016-02-18_01-05-21](https://cloud.githubusercontent.com/assets/6407980/13121259/d3c1e5dc-d5db-11e5-9927-27ef985c8f74.png)

I use Windows and I configured RustDT by [User Guide](https://github.com/RustDT/RustDT/blob/latest/documentation/UserGuide.md).

After build I have only one file `hello_world.exe` in `target\debug` folder and some small files in `target\debug\.fingerprint` folder.

For example `dep-bin-hello_world` file have next content

```
C:\Users\Alex\Documents\Home\Rust\hello_world

C:\Users\Alex\Documents\Home\Rust\hello_world\target\debug\hello_world.d: src\main.rs

src\main.rs:
```

How to configure Eclipse debugger on Windows to find Rust sources?

**Comment by bruno-medeiros** [comment]
So, what's happening here, is that the "main()" where the debugger is stopped is not the main function in your Rust code, but it's the C main(), the entry point for any executable. It's part of what is called the Rust runtime, and that main function is written in C (and doesn't have sources available). If you want to stop at the main of your Rust code, you should setup a breakpoint there, in the Rust source file. This is how it the debug trace will look:
![untitled3](https://cloud.githubusercontent.com/assets/4324232/13143039/224c9cee-d639-11e5-868a-6dd5fd368857.png)
You see you have the C `main()` at the bottom, but the Rust main is the `hello_world::main()` frame at the top

**Comment by AlexRadch** [comment]
Thank you! I found it my self.
But RustDT have other issue.

**It create incorrect path mapping to Rust 'src' directory.**
In Preferences I set up it to `C:\Users\Public\Documents\rustc-1.6.0-src\src` directory:
![2016-02-19_13-16-07](https://cloud.githubusercontent.com/assets/6407980/13168858/0956d60a-d70b-11e5-9246-7e930a610a31.png)

But when I try to debug with step into `println!("Hello, world!");` the eclipse `Can't find a source file at "C:\Users\rav1\Documents\Home\Rust\hello_world/../src/libcore\fmt/mod.rs"`
because RustDT create path mapping to `C:\Program Files\Rust stable GNU 1.6\src` directory, but do not create path mapping to `C:\Users\Public\Documents\rustc-1.6.0-src\src` directory.
![2016-02-19_13-24-00](https://cloud.githubusercontent.com/assets/6407980/13168978/1a4f4a22-d70c-11e5-8ba9-1b2e2efc1875.png)

So it should be corrected.

**Comment by bruno-medeiros** [comment]
Yup, that's a new bug.

**Comment by bruno-medeiros** [comment]
Yup, seems like that's a bug.
