### ISSUE TITLE
Failed to install on mac osx

### ISSUE THREAD

**Issue by nakalsio** [RustDT/RustDT#9]
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
error in opening zip file

**Comment by bruno-medeiros** [comment]
Maybe it was a temporary problem with Eclipse servers, can you try again? If not, please attach the whole Eclipse Error Log: https://github.com/RustDT/RustDT/blob/master/CONTRIBUTING.md#reporting-issues (you can use Gist to attach)

**Comment by bruno-medeiros** [comment]
Another possibility, are you in China? That could be the problem:
https://github.com/RustDT/RustDT/blob/latest/documentation/Installation.md#note-for-users-in-china

**Comment by bruno-medeiros** [comment]
Issue reference in commit 35977e7 above is incorrect
