### ISSUE TITLE
Project/executable with dash (-) in it fails to get breakpoints set

### ISSUE THREAD

**Issue by jrburke** [RustDT/RustDT#90]
In Eclipse Project Explorer on Mac OS X 10.11.3:

1) Right click, New Project, select Rust Cargo Project
- Project name: some-thing
- Location: Uncheck "Use default location". Chose a newly created directory at ~/git/some-thing
- Finish out the New Project wizard.

2) Modify Cargo.toml to rename `hello_world` to `some-thing`:

``` toml
[package]

name = "some-thing"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[[bin]]

name = "some-thing"
```

3) Toggle a breakpoint on main.rs line 2 (the println! example message).

4) In `Run, Debug Configurations...`:
- Change the Name from `some-thing - [hello_world]` to `some-thing - [some-thing]`
- In Main tab, set Path of launch executable to **not** have the "Use Build Target settings" checkbox checked, and change the path from `target/debug/hello_world` to `target/debug/some-thing`.
- In Debugger tab, set the full path to gdb.
- Apply change, then press Debug

---

The debugger does not stop at the breakpoint. Instead the program runs to completion. Checking the gdb output in the Debug view, this line shows up:

```
No source file named ~/git/some-thing/src/main.rs.
```

Which I believe is why the breakpoint is not set (note in the actual message, the ~ is actually the full file path, a path that does exist).

However, if the same steps are done, but with the name `something`, without the dash, it works.

Eclipse IDE for C/C++ Developers
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600
RustDT  0.5.1.v201602251459 com.github.rustdt.feature.group RustDT Project Team
GDB 7.10.1

**Comment by bruno-medeiros** [comment]
I just tried it and it works for me, although I'm using a different setup: GDB 7.9.1, and Windows.

In step 4), how did you create the launch configuration? Was it by double clicking in "Rust Application" ? Do you have any other breakpoints set? (if so, try again with just that one breakpoint)
What is the full output of the GDB console?

**Comment by jrburke** [comment]
Unfortunately my system has been wiped since first report and will not be able to reproduce, so closing the ticket.

**Comment by bruno-medeiros** [comment]
Yeah I tried it in Linux and it worked too. Might have been an outdated breakpoint configuration or something.
