### ISSUE TITLE
gdb is not working on ubuntu 14:04 - "Error disabling address space randomization"

### ISSUE THREAD

**Issue by eddiechristian** [RustDT/RustDT#94]
I followed the steps. why does it say '-Registering Rust pretty-printers for Windows' .....when I am running it on linux?

see this below?
143,863 14^error,msg="/tmp/rustdt_gdbinit_windows_811009088743949151:6: Error in sourced command fil\
e:\nError while executing Python code."

143,848 2-gdb-version
143,853 ~"GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1\n"
143,857 ~"Copyright (C) 2014 Free Software Foundation, Inc.\n"
143,857 ~"License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html\nThis is fre\
e software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitt\
ed by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
143,857 ~"This GDB was configured as \"x86_64-linux-gnu\".\nType \"show configuration\" for configur\
ation details."
143,857 ~"\nFor bug reporting instructions, please see:\n"
143,857 ~"http://www.gnu.org/software/gdb/bugs/.\n"
143,857 ~"Find the GDB manual and other documentation resources online at:\nhttp://www.gnu.org/soft
ware/gdb/documentation/.\n"
143,857 ~"For help, type \"help\".\n"
143,857 ~"Type \"apropos word\" to search for commands related to \"word\".\n"
143,857 2^done
143,857 (gdb) 
143,858 3-environment-cd /othello/othello
143,859 3^done
143,859 (gdb) 
143,859 4-gdb-set breakpoint pending on
143,859 4^done
143,859 (gdb) 
143,859 5-gdb-set detach-on-fork on
143,860 5^done
143,860 (gdb) 
143,860 6-enable-pretty-printing
143,860 6^done
143,860 (gdb) 
143,860 7-gdb-set python print-stack none
143,860 7^done
143,860 (gdb) 
143,860 8-gdb-set print object on
143,861 8^done
143,861 (gdb) 
143,861 9-gdb-set print sevenbit-strings on
143,861 9^done
143,861 (gdb) 
143,861 10-gdb-set host-charset UTF-8
143,861 10^done
143,861 (gdb) 
143,862 11-gdb-set target-charset US-ASCII
143,862 11^done
143,862 (gdb) 
143,862 12-gdb-set target-wide-charset UTF-32
143,862 12^done
143,862 (gdb) 
143,862 13-gdb-set dprintf-style call
143,862 13^done
143,862 (gdb) 
143,863 14source /tmp/rustdt_gdbinit_windows_811009088743949151
143,863 &"source /tmp/rustdt_gdbinit_windows_811009088743949151\n"
143,863 &"  File \"<string>\", line 1\n"
143,863 &"    print \"--Registering Rust pretty-printers for Windows--\"\n"
143,863 &"                                                           ^\n"
143,863 &"SyntaxError: Missing parentheses in call to 'print'\n"
143,863 &"/tmp/rustdt_gdbinit_windows_811009088743949151:6: Error in sourced command file:\n"
143,863 &"Error while executing Python code.\n"
143,863 14^error,msg="/tmp/rustdt_gdbinit_windows_811009088743949151:6: Error in sourced command fil\
e:\nError while executing Python code."
143,863 (gdb) 
143,863 15source .gdbinit
143,863 &"source .gdbinit\n"
143,864 16-gdb-set target-async off
143,865 &".gdbinit: No such file or directory.\n"
143,866 15^error,msg=".gdbinit: No such file or directory."
143,866 (gdb) 
143,866 16^done
143,866 (gdb) 
143,869 17-gdb-set auto-solib-add on
143,870 17^done
143,870 (gdb) 
143,870 18-file-exec-and-symbols --thread-group i1 /othello/othello/target/debug/hello_world
143,973 19-list-thread-groups
144,027 &"warning: Missing auto-load scripts referenced in section .debug_gdb_scripts\nof file /othe\
llo/othello/target/debug/hello_world\nUse `info auto-load python-scripts [REGEXP]' to list them."
144,027 &"\n"
144,027 18^done
144,027 (gdb) 
144,027 19^done,groups=[{id="i1",type="process",executable="/othello/othello/target/debug/hello_worl\
d"}]
144,027 (gdb) 
144,035 20-gdb-show --thread-group i1 language
144,035 20^done,value="auto"
144,035 (gdb) 
144,036 21-gdb-set --thread-group i1 language c
144,036 21^done
144,036 (gdb) 
144,038 22-interpreter-exec --thread-group i1 console "p/x (char)-1"
144,049 ~"$1 = 0xff\n"
144,050 22^done
144,050 (gdb) 
144,050 23-data-evaluate-expression --thread-group i1 "sizeof (void*)"
144,050 23^done,value="8"
144,050 (gdb) 
144,051 24-gdb-set --thread-group i1 language auto
144,051 24^done
144,051 (gdb) 
144,051 25-interpreter-exec --thread-group i1 console "show endian"
144,051 ~"The target endianness is set automatically (currently little endian)\n"
144,051 25^done
144,051 (gdb) 
144,055 26-break-insert -f /othello/othello/src/main.rs:6
144,198 26^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x00000000000048b9"\
,func="hello_world::main",file="src/main.rs",fullname="/othello/othello/src/main.rs",line="6",thread\
-groups=["i1"],times="0",original-location="/othello/othello/src/main.rs:6"}
144,198 (gdb) 
144,203 27-break-insert -t -f main
144,204 27^done,bkpt={number="2",type="breakpoint",disp="del",enabled="y",addr="0x0000000000004aa0",\
at="<main>",thread-groups=["i1"],times="0",original-location="main"}
144,204 (gdb) 
144,205 28-inferior-tty-set --thread-group i1 /dev/pts/0
144,205 28^done
144,205 (gdb) 
144,225 29-exec-run --thread-group i1
144,247 &"warning: Error disabling address space randomization: Operation not permitted\n"
144,253 =thread-group-started,id="i1",pid="819"
144,254 =thread-created,id="1",group-id="i1"
144,255 30-list-thread-groups --available
144,311 31-list-thread-groups
144,316 =thread-exited,id="1",group-id="i1"
144,316 =thread-group-exited,id="i1"
144,321 29^error,msg="During startup program exited normally."
144,321 (gdb) 
144,321 30^done,groups=[{id="1",type="process",description="/bin/bash",user="root",cores=["0"]},{id=\
"14",type="process",description="eclipse",user="root",cores=["0"]},{id="15",type="process",descripti\
on="/opt/jdk1.8.0_73/jre/bin/java -Dosgi.requiredJavaVersion=1.7 -XX:MaxPermSize=256m -Xms256m -Xmx1\
024m -jar /opt/eclipse//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -os linux -w\
s gtk -arch x86_64 -showsplash /opt/eclipse//plugins/org.eclipse.platform_4.5.2.v20160212-1500/splas\
h.bmp -launcher /opt/eclipse/eclipse -name Eclipse --launcher.library /opt/eclipse//plugins/org.ecli\
pse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so -startup /opt/eclipse//\
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar --launcher.appendVmargs -exitdata 0 \
-product org.eclipse.epp.package.cpp.product -vm /opt/jdk1.8.0_73/jre/bin/java -vmargs -Dosgi.requir\
edJavaVersion=1.7 -XX:MaxPermSize=256m -Xms256m -Xmx1024m -jar /opt/eclipse//plugins/org.eclipse.equ\
inox.launcher_1.3.100.v20150511-1540.jar",user="root",cores=["0"]},{id="804",type="process",descript\
ion="gdb --interpreter mi2 --nx",user="root",cores=["0"]}]
144,322 (gdb) 
144,322 31^done,groups=[{id="i1",type="process",executable="/othello/othello/target/debug/hello_worl\
d"}]
144,322 (gdb) 
144,376 32-gdb-exit
144,382 32^exit

**Comment by eddiechristian** [comment]
the breakpoint is not being set?

**Comment by bruno-medeiros** [comment]
> I followed the steps. why does it say '-Registering Rust pretty-printers for Windows' .....when I am running it on linux?

Yes, this is definitely not right. But I'm not sure it's related to the problem you're actually experiencing. 

Did you setup a breakpoint in /othello/othello/src/main.rs:6 and the execution didn't stop there, is that the problem? Did the program terminate without stopping on anything? What's the contents of your main.rs?

**Comment by eddiechristian** [comment]
very simple test program. It should not matter that eclipse is being run on a headless ubuntu vm with its workspace directory shared from mac host?

fn main() {
    let x :i32 = 5;

```
println!("x: {:?}",x);
let y: i32 = 6;
println!("y: {:?}",y);
println!("Hello, world!");
```

}

**Comment by bruno-medeiros** [comment]
Well, I guess it should work, unless it's a problem with GDB or Rust itself. Which Rust version are you using? Can you try the same code and breakpoint with a command-line GDB, to see if works there?

**Comment by iskunk** [comment]
> Error disabling address space randomization: Operation not permitted

http://stackoverflow.com/questions/35860527/warning-error-disabling-address-space-randomization-operation-not-permitted/35860616

https://rubicks.github.io/post/docker-run-privileged-gdb/

**Comment by bruno-medeiros** [comment]
@iskunk Thanks so much for that information! I get a lot of debugging issues opened for RustDT (and Goclipse), and most of the time they seem to be GDB-specific, not Eclipse related. Especially as GDB has many quirks that depend on the OS. (and normally I only run it on Windows)

**Comment by iskunk** [comment]
Glad to help! I was dealing with this problem as well, and this thread came up alongside the articles explaining what was going on. It was an easy loop to close :-)
