### ISSUE TITLE
Feature: Add custom "Build Targets"

### ISSUE THREAD

**Issue by JinShil** [RustDT/RustDT#95]
I can't seem to find a way to create new build targets for a project, or edit the name of existing build targets.    I suppose I could edit the XML in the _com.github.rustdt.ide.core.prefs_ file, but I was wondering if there was a way to do this in the IDE.

**Comment by bruno-medeiros** [comment]
Nope, you can't add new Build Targets, you can only configure the arguments of the pre-defined targets (right-click, "Configure Target...").
But one of the next features I was to implement is this, adding custom build targets.
