### ISSUE TITLE
Running Targets from "crate#tests" failed in OS X

### ISSUE THREAD

**Issue by redtankd** [RustDT/RustDT#96]
I use Eclipse 4.5 in OS X 10.11. When I run Build Targets "crate#tests", the menu display "Run test[bin.test" - target/debug/<Error:found multiple executable files for test target>" .

So I check the path "target/debug/" and find a file "test-381f50a00b28113f" and a directory "test-381f50a00b28113f.dSYM".

I google the error message "found multiple executable files for test target" and then come to "RustDT/plugin_tooling/src/com/github/rustdt/tooling/cargo/CargoTargetHelper.java".  The lines 63 to 77 are below:

```
        String[] matchingExes = crateLocation.resolve(exeDirectory).toFile().list(new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.startsWith(exePrefix + "-");
            }
        });

        String testFilename;
        if(matchingExes == null || matchingExes.length == 0) {
            testFilename = "<Error: could not determine executable file for test target>";
        } else if(matchingExes.length > 1) {
            testFilename = "<Error: found multiple executable files for test target>";
        } else {
            testFilename = matchingExes[0];
        }
```

Maybe "return name.startsWith(exePrefix + "-");" is the culprit.

**Comment by bruno-medeiros** [comment]
Yeah, I'm waiting for this to be fixed: https://github.com/rust-lang/cargo/issues/1924#issuecomment-198328446 so the IDE can know exactly which one is the executable file, instead of trying to guess.

In the meanwhile, hum, I could add another check to accept to see if the path is a directory or not. This should fix things for OSX
