### ISSUE TITLE
Tabs not always converted to spaces

### ISSUE THREAD

**Issue by mpartel** [RustDT/RustDT#99]
When I hit the tab key, I get a tab character instead of spaces.

I've set indentation to "Spaces" in `Rust -> Editor -> Typing`, and I've checked "Insert spaces for tabs" in `General -> Editors -> Text Editors`.

RustDT 0.5.1.v201602251459

**Comment by 2bdkid** [comment]
I'm getting the same problem.
Eclipse Platform 4.5 
RustDT 0.5.1.v201602251459

**Comment by bruno-medeiros** [comment]
Found it. 

There's a workaround: Go to Preferences/General/Keys , add "Tab" binding to "Shift Right" command, and "Shift+Tab" binding to "Shift Left" command. Both of these you can restrict to just a Rust context of "Editing Rust source"

**Comment by bruno-medeiros** [comment]
Actually the above is not a proper workaround, as it will prevent you from inserting an actual TAB character in the middle of the line.
